-- Seed all static CAH cards into cah_cards.
-- Run after 001_cah_cards.sql.
-- Uses ON CONFLICT DO NOTHING so it is safe to re-run.

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('b001','base','black','What''s that smell?',1),
('b002','base','black','I got 99 problems but _ ain''t one.',1),
('b003','base','black','What are my parents hiding from me?',1),
('b004','base','black','What don''t you want to find in your trick-or-treat bag?',1),
('b005','base','black','What gives me uncontrollable gas?',1),
('b006','base','black','What did I bring back from Mexico?',1),
('b007','base','black','Why am I sticky?',1),
('b008','base','black','What''s the next Happy Meal toy?',1),
('b009','base','black','Here is the church, here is the steeple, open the doors, and there is _.',1),
('b010','base','black','What ended my last relationship?',1),
('b011','base','black','What''s fun until it gets weird?',1),
('b012','base','black','What does Dick Cheney prefer?',1),
('b013','base','black','Before I''ll get in the pool, I have to make sure there''s no _.',1),
('b014','base','black','DearÚrsula, I am writing to inform you that your daughter is a raging _.',1),
('b015','base','black','I drink to forget _.',1),
('b016','base','black','Instead of coal, Santa now gives bad children _.',1),
('b017','base','black','TSA guidelines now prohibit _ on airplanes.',1),
('b018','base','black','What do old people smell like?',1),
('b019','base','black','What will always get you laid?',1),
('b020','base','black','I never truly understood _ until I encountered _.',2),
('b021','base','black','What''s a girl''s best friend?',1),
('b022','base','black','In the beginning there was _, and it was good.',1),
('b023','base','black','My new favourite cocktail: equal parts _ and _.',2),
('b024','base','black','After the earthquake, we had nothing left but _ and _.',2),
('b025','base','black','What is Batman''s guilty pleasure?',1),
('b026','base','black','In a world ravaged by _, our only solace is _.',2),
('b027','base','black','What am I giving up for Lent?',1),
('b028','base','black','What would grandma find disturbing, yet oddly charming?',1),
('b029','base','black','What''s the cruelest thing you can do to a friend?',1),
('b030','base','black','Lifetime presents: _, the story of _.',2),
('b031','base','black','Forget world peace. If I had a genie, I''d wish for _.',1),
('b032','base','black','What has been making life difficult at the nudist colony?',1),
('b033','base','black','What''s making things awkward in the sauna?',1),
('b034','base','black','What did the health inspector find in the kitchen?',1),
('b035','base','black','How did I lose my virginity?',1),
('b036','base','black','In his latest book, Malcolm Gladwell argues that _ is the root cause of _ .',2),
('b037','base','black','What''s the most emo?',1),
('b038','base','black','After much deliberation, we have decided to add _ to the menu.',1),
('b039','base','black','What did I find in the back of the closet?',1),
('b040','base','black','What makes every family gathering awkward?',1),
('b041','base','black','What''s the new fad diet?',1),
('b042','base','black','_ + _ = _.',3),
('b043','base','black','Introducing Pringles new flavour: _.',1),
('b044','base','black','What do I get from a good day''s work?',1),
('b045','base','black','A recent survey says that 9 out of 10 Americans prefer _ to _.',2),
('b046','base','black','What does the Sorting Hat say to the new Hogwarts students?',1),
('b047','base','black','What has been making the morning commute awkward lately?',1),
('b048','base','black','In the future, scientists will engineer chickens that are born pre-stuffed with _.',1),
('b049','base','black','What is the secret to a lasting marriage?',1),
('b050','base','black','Next on ESPN2: the World Series of _.',1),
('b051','base','black','What does Miley Cyrus have that I don''t?',1),
('b052','base','black','When I was growing up, instead of Santa Claus, we had _.',1),
('b053','base','black','Why do I hurt all over?',1),
('b054','base','black','What''s the most important quality in a partner?',1),
('b055','base','black','In a pinch, _ can be a suitable replacement for _.',2),
('b056','base','black','What keeps the cast of Jersey Shore going?',1),
('b057','base','black','What did I put in my mouth that I immediately regretted?',1),
('b058','base','black','What do I think about when I can''t fall asleep?',1),
('b059','base','black','I''m pretty sure the zombie apocalypse started with _.',1),
('b060','base','black','What''s the plot of the summer blockbuster?',1),
('b061','base','black','How am I compensating for my tiny penis?',1),
('b062','base','black','Kids these days, with their _ and their _.',2),
('b063','base','black','What is my secret power?',1),
('b064','base','black','What gets better with age?',1),
('b065','base','black','Step 1: _. Step 2: _. Step 3: Profit.',2),
('b066','base','black','What do hipsters do on a Saturday night?',1),
('b067','base','black','I would like to thank _ for _ during my acceptance speech.',2),
('b068','base','black','What will I regret most on my deathbed?',1),
('b069','base','black','After the catastrophe, the only thing that remained was _.',1),
('b070','base','black','What did the Buddhist say to the hot dog vendor?',1),
('b071','base','black','I''m sorry, Professor, but I couldn''t complete my homework because of _.',1),
('b072','base','black','During Passover, we eat no leavened bread and we remember _.',1),
('b073','base','black','What is the geekiest thing you have ever done?',1),
('b074','base','black','What did the pirate say?',1),
('b075','base','black','What would you like to order?',1),
('b076','base','black','What has the greatest WiFi?',1),
('b077','base','black','Why am I going to jail?',1),
('b078','base','black','What is the most important policy issue in today''s debate?',1),
('b079','base','black','What do I tell people my start-up is about?',1),
('b080','base','black','I do not know with what weapons World War III will be fought, but World War IV will be fought with _.',1),
('b081','base','black','Coming to Broadway: the story of one woman''s struggle with _ and her ultimate victory over _.',2),
('b082','base','black','Man, I hate it when _ gets in my _ .',2),
('b083','base','black','How did I finally lose all that weight?',1),
('b084','base','black','What''s always a surprise at a surprise party?',1),
('b085','base','black','What is love?',1),
('b086','base','black','What is that sound?',1),
('b087','base','black','What never gets old?',1),
('b088','base','black','In M. Night Shyamalan''s new film, Bruce Willis discovers that _ had been _ the whole time.',2),
('b089','base','black','What is my dad''s job?',1),
('b090','base','black','What is the most important thing to sign before surgery?',1),
('w001','base','white','A disappointing birthday party.',1),
('w002','base','white','A sassy black woman.',1),
('w003','base','white','Pretending to care.',1),
('w004','base','white','The weird feeling you get when someone is clearly lying.',1),
('w005','base','white','Alcoholism.',1),
('w006','base','white','Passive-aggressive Post-it notes.',1),
('w007','base','white','A subscription to your enemies'' problems.',1),
('w008','base','white','Racially-biased standardized tests.',1),
('w009','base','white','Being on fire.',1),
('w010','base','white','Genital to genital contact.',1),
('w011','base','white','White privilege.',1),
('w012','base','white','Hope.',1),
('w013','base','white','Frolicking.',1),
('w014','base','white','Inappropriate yelling.',1),
('w015','base','white','Authentic Mexican flavour.',1),
('w016','base','white','Ronald McDonald.',1),
('w017','base','white','Explosions.',1),
('w018','base','white','The female orgasm.',1),
('w019','base','white','Chunks.',1),
('w020','base','white','Mr. Clean.',1),
('w021','base','white','A cooler full of organs.',1),
('w022','base','white','The class pet.',1),
('w023','base','white','An honest answer.',1),
('w024','base','white','Nipple blades.',1),
('w025','base','white','Vigorous jazz hands.',1),
('w026','base','white','Poverty.',1),
('w027','base','white','Classist undertones.',1),
('w028','base','white','Fifty years of true love.',1),
('w029','base','white','One thousand Slim Shadys.',1),
('w030','base','white','Waking up half-naked in a Denny''s parking lot.',1),
('w031','base','white','Finger-banging.',1),
('w032','base','white','Estrogen.',1),
('w033','base','white','Foreskin.',1),
('w034','base','white','The inevitable heat death of the universe.',1),
('w035','base','white','Science.',1),
('w036','base','white','A really cool hat.',1),
('w037','base','white','Eating all of the cookies before the rest of the family gets home.',1),
('w038','base','white','Bees?',1),
('w039','base','white','German dungeon porn.',1),
('w040','base','white','Swiftly achieving orgasm.',1),
('w041','base','white','Flying sex snakes.',1),
('w042','base','white','Ethnic cleansing.',1),
('w043','base','white','Natural lube.',1),
('w044','base','white','Powerful thighs.',1),
('w045','base','white','The whole Mormon thing.',1),
('w046','base','white','The shambling corpse of Larry King.',1),
('w047','base','white','Praying the gay away.',1),
('w048','base','white','Getting paid.',1),
('w049','base','white','Menstruation.',1),
('w050','base','white','Repression.',1),
('w051','base','white','My first period.',1),
('w052','base','white','Dry anal.',1),
('w053','base','white','Public masturbation.',1),
('w054','base','white','Horse-sized ducks.',1),
('w055','base','white','Being a dinosaur.',1),
('w056','base','white','Republicans.',1),
('w057','base','white','Dead parents.',1),
('w058','base','white','Puppies!',1),
('w059','base','white','Leprosy.',1),
('w060','base','white','The situation in the Middle East.',1),
('w061','base','white','Smallpox blankets.',1),
('w062','base','white','Unsubstantiated medical advice.',1),
('w063','base','white','Sean Connery.',1),
('w064','base','white','Living in a dream world.',1),
('w065','base','white','Literally getting away with murder.',1),
('w066','base','white','Dick Cheney.',1),
('w067','base','white','Teaching your dog to say ''I love you''.',1),
('w068','base','white','Heteronormativity.',1),
('w069','base','white','Lactation.',1),
('w070','base','white','God.',1),
('w071','base','white','Her Majesty, Queen Elizabeth II.',1),
('w072','base','white','The total and complete loss of hope.',1),
('w073','base','white','Taking a ramen noodle bath.',1),
('w074','base','white','Flesh-eating bacteria.',1),
('w075','base','white','Heterosexual privilege.',1),
('w076','base','white','Masturbating into a pool of tears.',1),
('w077','base','white','The glass ceiling.',1),
('w078','base','white','Winking at old people.',1),
('w079','base','white','Being rich.',1),
('w080','base','white','Eating ice cream alone in the dark.',1),
('w081','base','white','Two midgets trying to get into a car.',1),
('w082','base','white','Surprise sex!',1),
('w083','base','white','The look on my dog''s face when he smells another dog''s butthole.',1),
('w084','base','white','Tossing the first stone.',1),
('w085','base','white','Dying.',1),
('w086','base','white','Waiting until marriage.',1),
('w087','base','white','Being creepily nice.',1),
('w088','base','white','Cheating in the Special Olympics.',1),
('w089','base','white','Pretending to orgasm.',1),
('w090','base','white','A really strong orgasm.',1),
('w091','base','white','An erection that lasts longer than four hours.',1),
('w092','base','white','Jibber-jabber.',1),
('w093','base','white','Getting drunk on mouthwash.',1),
('w094','base','white','A detailed note on how to make a bomb.',1),
('w095','base','white','An old man''s soupçon of dignity.',1),
('w096','base','white','My manservant, Claude.',1),
('w097','base','white','A tiny horse.',1),
('w098','base','white','My ex-wife''s alimony payments.',1),
('w099','base','white','Nicolas Cage.',1),
('w100','base','white','Forgetting to take the baby out of the car.',1),
('w101','base','white','Racism.',1),
('w102','base','white','A windmill full of corpses.',1),
('w103','base','white','Nunchucks.',1),
('w104','base','white','Assless chaps.',1),
('w105','base','white','The musk of a Viking warrior.',1),
('w106','base','white','Passive-aggression.',1),
('w107','base','white','A sweet ass.',1),
('w108','base','white','The Hamburglar.',1),
('w109','base','white','A home circumcision kit.',1),
('w110','base','white','A falcon with a cap on.',1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('w111','base','white','The heart of a child.',1),
('w112','base','white','Oomph.',1),
('w113','base','white','Nickelback.',1),
('w114','base','white','Meth.',1),
('w115','base','white','A bag of magic beans.',1),
('w116','base','white','Sexy pillow fights.',1),
('w117','base','white','Count Chocula.',1),
('w118','base','white','Lance Armstrong''s missing testicle.',1),
('w119','base','white','Amputees.',1),
('w120','base','white','A snapping turtle biting the tip of your penis.',1),
('w121','base','white','Dead babies.',1),
('w122','base','white','Not giving a shit about the Third World.',1),
('w123','base','white','The Big Bang.',1),
('w124','base','white','My relationship with Jesus.',1),
('w125','base','white','Firing a man cannon.',1),
('w126','base','white','Funky-smelling nipples.',1),
('w127','base','white','Warlords.',1),
('w128','base','white','Poorly-timed Holocaust jokes.',1),
('w129','base','white','Jews.',1),
('w130','base','white','Exactly what you''d expect.',1),
('w131','base','white','Waiting until she''s asleep.',1),
('w132','base','white','Syphilis.',1),
('w133','base','white','Hormone therapy.',1),
('w134','base','white','A fetus.',1),
('w135','base','white','The Trail of Tears.',1),
('w136','base','white','Getting really high and learning to jump-start a car.',1),
('w137','base','white','My inner demons.',1),
('w138','base','white','Letting yourself go.',1),
('w139','base','white','Genital warts.',1),
('w140','base','white','Barack Obama.',1),
('w141','base','white','Sweet, sweet vengeance.',1),
('w142','base','white','A balanced breakfast.',1),
('w143','base','white','Extremely tight pants.',1),
('w144','base','white','Being a dragon.',1),
('w145','base','white','A really mediocre guy.',1),
('w146','base','white','Whatever the Germans have instead of schadenfreude.',1),
('w147','base','white','The patriarchy.',1),
('w148','base','white','My collection of high-quality pornography.',1),
('w149','base','white','A gyrating pelvis.',1),
('w150','base','white','Eating the last piece without asking.',1),
('w151','base','white','Not wearing a condom.',1),
('w152','base','white','Warm, velvety mink.',1),
('w153','base','white','The harsh light of day.',1),
('w154','base','white','Glenn Beck''s tears.',1),
('w155','base','white','Being marginalized.',1),
('w156','base','white','A leprechaun smoking a cigar on a throne of gold.',1),
('w157','base','white','A flaming bag of dog shit.',1),
('w158','base','white','Growing up without a father.',1),
('w159','base','white','Old people smell.',1),
('w160','base','white','Making a friend.',1),
('w161','base','white','Turning into a sausage.',1),
('w162','base','white','Picking up a dog poo with your bare hand.',1),
('w163','base','white','Accidentally pooping.',1),
('w164','base','white','Punching a hole through the moon.',1),
('w165','base','white','The Jews.',1),
('w166','base','white','AIDS.',1),
('w167','base','white','A time machine that only goes to the worst historical periods.',1),
('w168','base','white','Inserting a _____ into a _____.',1),
('w169','base','white','The experience of going to Applebee''s.',1),
('w170','base','white','Using one eye to look into the past and one to see the future.',1),
('w171','base','white','Chunks of a dead prostitute.',1),
('w172','base','white','Feeding Bibles to the homeless.',1),
('w173','base','white','Copping a feel.',1),
('w174','base','white','A Bulbasaur.',1),
('w175','base','white','The American Dream.',1),
('w176','base','white','A really sloppy Joe.',1),
('w177','base','white','The terrorists.',1),
('w178','base','white','Wasting entire days on the internet.',1),
('w179','base','white','Sexy, sexy robots.',1),
('w180','base','white','Rehab.',1),
('w181','base','white','A fat man in a Speedo.',1),
('w182','base','white','Emotional baggage.',1),
('w183','base','white','Running away from my problems.',1),
('w184','base','white','Unfathomable stupidity.',1),
('w185','base','white','Skeletons that can dance.',1),
('w186','base','white','Edible underpants.',1),
('w187','base','white','A giant, steaming pile of bingo cards.',1),
('w188','base','white','An Oedipus complex.',1),
('w189','base','white','Being Jewish.',1),
('w190','base','white','When you forget the safeword.',1),
('w191','base','white','The dark arts.',1),
('w192','base','white','Insincere apologies.',1),
('w193','base','white','Lunchables.',1),
('w194','base','white','A dog in a bee costume.',1),
('w195','base','white','Pooping back and forth forever.',1),
('w196','base','white','Poorly-executed foreplay.',1),
('w197','base','white','Tasteful sideboob.',1),
('w198','base','white','Catastrophic urethral failure.',1),
('w199','base','white','All of this blood.',1),
('w200','base','white','The taint, the grundle, the grundulum.',1),
('w201','base','white','Auschwitz.',1),
('w202','base','white','Pubic hair.',1),
('w203','base','white','A cartoon caricature of a black person.',1),
('w204','base','white','Spontaneous human combustion.',1),
('w205','base','white','A lifetime of sadness.',1),
('w206','base','white','A face full of crazy.',1),
('w207','base','white','Tentacle porn.',1),
('w208','base','white','Throwing a virgin into a volcano.',1),
('w209','base','white','A majestic eagle.',1),
('w210','base','white','What Jesus would have done.',1),
('w211','base','white','A bleached asshole.',1),
('w212','base','white','Silence.',1),
('w213','base','white','William Shatner.',1),
('w214','base','white','Dry heaving.',1),
('w215','base','white','A monkey driving a truck.',1),
('w216','base','white','Slowly giving up.',1),
('w217','base','white','Date rape.',1),
('w218','base','white','Men.',1),
('w219','base','white','Vigorous masturbation.',1),
('w220','base','white','The profoundly handicapped.',1),
('w221','base','white','A syringe of Axe body spray.',1),
('w222','base','white','Explosive diarrhea.',1),
('w223','base','white','The clitoris.',1),
('w224','base','white','Queefing.',1),
('w225','base','white','Being sexually attracted to Batman.',1),
('w226','base','white','Chainsaws for hands.',1),
('w227','base','white','The true nature of the universe.',1),
('w228','base','white','A disappointing son.',1),
('w229','base','white','Being fat and stupid.',1),
('w230','base','white','Overcompensation.',1),
('w231','base','white','The miracle of childbirth.',1),
('w232','base','white','Forgetting to use a condom.',1),
('w233','base','white','Stabbing someone.',1),
('w234','base','white','Battered Spouse Syndrome.',1),
('w235','base','white','Oppression.',1),
('w236','base','white','The hardworking genitalia of Mexican immigrants.',1),
('w237','base','white','Surprise buttsex.',1),
('w238','base','white','Bitches.',1),
('w239','base','white','A gentle caress.',1),
('w240','base','white','Fiery poops.',1),
('w241','base','white','Dying alone.',1),
('w242','base','white','Hot cheese.',1),
('w243','base','white','Making a baby cry.',1),
('w244','base','white','The Pope.',1),
('w245','base','white','A picture of your genitals.',1),
('w246','base','white','Involuntary erections.',1),
('w247','base','white','The invisible hand of the free market.',1),
('w248','base','white','An intimate dinner for two.',1),
('w249','base','white','A tiny, hilariously-large phone.',1),
('w250','base','white','The hard-knock life.',1),
('w251','base','white','Not reciprocating oral sex.',1),
('w252','base','white','Crystal meth.',1),
('w253','base','white','Friends who eat all your food.',1),
('w254','base','white','The violation of our most basic human rights.',1),
('w255','base','white','A can of whoop-ass.',1),
('w256','base','white','Seductive eyebrows.',1),
('w257','base','white','Getting drunk on a Tuesday.',1),
('w258','base','white','Prancing.',1),
('w259','base','white','Dying of dysentery.',1),
('w260','base','white','My collection of foreign stamps.',1),
('w261','base','white','Googling ''what is a clitoris''.',1),
('w262','base','white','An enormous amount of cocaine.',1),
('w263','base','white','A death ray.',1),
('w264','base','white','Murdering a hobo.',1),
('w265','base','white','The number of people I''ve slept with.',1),
('w266','base','white','Sticking a needle in your arm.',1),
('w267','base','white','Making a woman sad.',1),
('w268','base','white','Holding down a girl.',1),
('w269','base','white','Smegma.',1),
('w270','base','white','Getting so angry you can''t speak.',1),
('w271','base','white','Sharing needles.',1),
('w272','base','white','A giant robot penis.',1),
('w273','base','white','The weird conversation at the end of a one-night stand.',1),
('w274','base','white','Accidentally reading the Bible.',1),
('w275','base','white','Goblins.',1),
('w276','base','white','The underground railroad.',1),
('w277','base','white','The blood of our enemies.',1),
('w278','base','white','Fisting.',1),
('w279','base','white','The tears of a clown.',1),
('w280','base','white','Being the little spoon.',1),
('w281','base','white','The life-giving power of the Sun.',1),
('w282','base','white','Drinking alone.',1),
('w283','base','white','Falling in love.',1),
('w284','base','white','Teaching a horse to cheat at poker.',1),
('w285','base','white','The cool parts of the Bible.',1),
('w286','base','white','A really good lawyer.',1),
('w287','base','white','Churning butter.',1),
('w288','base','white','Feelings.',1),
('w289','base','white','Apologizing.',1),
('w290','base','white','The big one.',1),
('w291','base','white','My sex face.',1),
('w292','base','white','Peeing a little bit.',1),
('w293','base','white','Waking up and forgetting where I am.',1),
('w294','base','white','Old-people sex.',1),
('w295','base','white','A fleshlight.',1),
('w296','base','white','Children on leashes.',1),
('w297','base','white','Tying the knot.',1),
('w298','base','white','A box of kittens.',1),
('w299','base','white','An unhappy ending.',1),
('w300','base','white','Human rights violations.',1),
('w301','base','white','Throwing up into someone''s hair.',1),
('w302','base','white','Getting fingered by Edward Scissorhands.',1),
('w303','base','white','The gays.',1),
('w304','base','white','Doing the right thing.',1),
('w305','base','white','A poodle of some kind.',1),
('w306','base','white','The last slice of pizza.',1),
('w307','base','white','A disappointed look.',1),
('w308','base','white','Getting established.',1),
('w309','base','white','Puberty.',1),
('w310','base','white','Crying while eating.',1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('w311','base','white','Throwing away your dreams.',1),
('w312','base','white','Seeing Mama Cass eat a ham sandwich.',1),
('w313','base','white','Former President George W. Bush.',1),
('w314','base','white','Eating all the food.',1),
('w315','base','white','Abstinence-only sex education.',1),
('w316','base','white','Chunks of a fresh maxi-pad.',1),
('w317','base','white','A really big fork.',1),
('w318','base','white','A baby crying.',1),
('w319','base','white','Roofies.',1),
('w320','base','white','Taking a giant dump.',1),
('w321','base','white','Holding someone down.',1),
('w322','base','white','Jerking off into a pool of tears.',1),
('w323','base','white','The milk of human kindness.',1),
('w324','base','white','Hissing yourself awake.',1),
('w325','base','white','A Yelp review of the Holocaust.',1),
('w326','base','white','A look of religious ecstasy.',1),
('w327','base','white','Flesh.',1),
('w328','base','white','Apologetic diarrhea.',1),
('w329','base','white','Being poor.',1),
('w330','base','white','A gassy German man.',1),
('w331','base','white','Pummelling the shit out of someone.',1),
('w332','base','white','Balls.',1),
('w333','base','white','Eating pussy.',1),
('w334','base','white','Vigorous ass-slapping.',1),
('w335','base','white','Not realising that the Holocaust was actually pretty bad.',1),
('w336','base','white','A sad orphan.',1),
('w337','base','white','Being on too many medications at once.',1),
('w338','base','white','A 55-gallon drum of lube.',1),
('w339','base','white','Molestation.',1),
('w340','base','white','Tom Cruise.',1),
('w341','base','white','The human body.',1),
('w342','base','white','Pretending to be happy.',1),
('w343','base','white','Dead babies.',1),
('w344','base','white','A sassy black woman who don''t take no shit.',1),
('w345','base','white','Eugenics.',1),
('w346','base','white','Sneezing, farting, and orgasming at the same time.',1),
('w347','base','white','Unprotected sex with multiple partners.',1),
('w348','base','white','The moon.',1),
('w349','base','white','Weeaboos.',1),
('w350','base','white','Multiple stab wounds.',1),
('w351','base','white','A sewer of broken dreams.',1),
('w352','base','white','The three R''s: Reading, Writing, and Arson.',1),
('w353','base','white','Human-animal hybrids.',1),
('w354','base','white','Pac-Man uncontrollably guzzling cum.',1),
('w355','base','white','Fiery poops.',1),
('w356','base','white','Eating someone''s hair.',1),
('w357','base','white','The 72 virgins.',1),
('w358','base','white','Grandma''s dentures.',1),
('w359','base','white','A beige cardigan.',1),
('w360','base','white','A dragon that breathes fire, and also is racist.',1),
('w361','base','white','Morgan Freeman''s voice.',1),
('w362','base','white','Wearing a birthday suit in a non-birthday context.',1),
('w363','base','white','A sad, sad man.',1),
('w364','base','white','Ruining the sex mood with bad techno music.',1),
('w365','base','white','A tribe of warrior women.',1),
('w366','base','white','Not enough lube.',1),
('w367','base','white','Forgetting to pull out.',1),
('w368','base','white','A porcupine getting a bikini wax.',1),
('w369','base','white','The hardworking men and women of the armed forces.',1),
('w370','base','white','Bitchy resting face.',1),
('w371','base','white','Too much pie.',1),
('w372','base','white','Hurricane Katrina.',1),
('w373','base','white','Masturbation.',1),
('w374','base','white','Three wolf moon.',1),
('w375','base','white','A jar of bees.',1),
('w376','base','white','Swallowing the evidence.',1),
('w377','base','white','The creamy white goodness of milk.',1),
('w378','base','white','Gaping anuses.',1),
('w379','base','white','Strained analogies.',1),
('w380','base','white','Waiting your whole life for your ship to come in.',1),
('w381','base','white','The clap.',1),
('w382','base','white','Not using enough lube.',1),
('w383','base','white','A series of beeps and boops.',1),
('w384','base','white','Using a body as fertiliser.',1),
('w385','base','white','Forgetting to wash your hands.',1),
('w386','base','white','Oompa Loompas.',1),
('w387','base','white','Getting so drunk you pee yourself.',1),
('w388','base','white','The gentle lapping of waves at the seashore.',1),
('w389','base','white','BATMAN!!!',1),
('w390','base','white','A whole new world.',1),
('w391','base','white','Learning about the birds and the bees.',1),
('w392','base','white','One glass of punch.',1),
('w393','base','white','Going ape-shit on someone.',1),
('w394','base','white','A world without men.',1),
('w395','base','white','Peeing into a pool.',1),
('w396','base','white','Death by snoo-snoo.',1),
('w397','base','white','Pixelated celebrity genitalia.',1),
('w398','base','white','A delicious peach.',1),
('w399','base','white','Giving a rusty trombone.',1),
('w400','base','white','Being black.',1),
('w401','base','white','My humps.',1),
('w402','base','white','Wet sand.',1),
('w403','base','white','A dolphin''s smile.',1),
('w404','base','white','A finger in the bum.',1),
('w405','base','white','Seeing a gingerbread house in the forest and thinking, ''For real?''',1),
('w406','base','white','Skipping down the street.',1),
('w407','base','white','Big black dicks.',1),
('w408','base','white','Michael Jordan''s retirement from basketball.',1),
('w409','base','white','Going to a Taylor Swift concert alone.',1),
('w410','base','white','Blacking out.',1),
('w411','base','white','Not having friends.',1),
('w412','base','white','A trip to the moon.',1),
('w413','base','white','Being mean to someone for a laugh.',1),
('w414','base','white','Masturbating into a copy of the Bible.',1),
('w415','base','white','Forgetting someone''s name.',1),
('w416','base','white','A fat child getting stuck in a slide.',1),
('w417','base','white','A big pile of shit.',1),
('w418','base','white','Being a Furry.',1),
('w419','base','white','Setting the record for most consecutive days of sadness.',1),
('w420','base','white','The hardest part of a Ph.D.',1),
('w421','base','white','One-sided love.',1),
('w422','base','white','Something that never gets old.',1),
('w423','base','white','Loving yourself.',1),
('w424','base','white','The ghost of Ronald Reagan.',1),
('w425','base','white','Using sex to solve problems.',1),
('w426','base','white','The soul train.',1),
('w427','base','white','Putting things up your butt.',1),
('w428','base','white','Pulling out.',1),
('w429','base','white','Cutting off your own hand.',1),
('w430','base','white','Being responsible.',1),
('w431','base','white','Just the tip.',1),
('w432','base','white','Sleeping in.',1),
('w433','base','white','My dog''s balls.',1),
('w434','base','white','Being kicked out of the country.',1),
('w435','base','white','Using your mind for evil.',1),
('w436','base','white','Grinding on someone without their consent.',1),
('w437','base','white','A beautiful face.',1),
('w438','base','white','Boobs.',1),
('w439','base','white','Making someone''s childhood vaguely unsettling.',1),
('w440','base','white','A spooky ghost.',1),
('w441','base','white','Bono.',1),
('w442','base','white','Extreme body horror.',1),
('w443','base','white','The feeling of sand between your toes.',1),
('w444','base','white','Taking off the condom halfway through.',1),
('w445','base','white','Getting drunk on a school night.',1),
('w446','base','white','A time paradox.',1),
('w447','base','white','A butt plug shaped like Franklin D. Roosevelt.',1),
('w448','base','white','Pretending not to notice.',1),
('w449','base','white','The placebo effect.',1),
('w450','base','white','Taking off your pants.',1),
('w451','base','white','Cruelty.',1),
('w452','base','white','Me time.',1),
('w453','base','white','Forgetting everything.',1),
('w454','base','white','The American flag.',1),
('w455','base','white','Firing all the missiles.',1),
('w456','base','white','Chunks from a fresh bag of M&Ms.',1),
('w457','base','white','Looking like you are asleep but actually being dead.',1),
('w458','base','white','Smiling politely.',1),
('w459','base','white','A terrible medical decision.',1),
('w460','base','white','Unlimited power.',1),
('sv-b001','swedish','black','Min mest romantiska dejt innehöll en finare middag och _.',1),
('sv-b002','swedish','black','Snart på bio, ”_ – andra sommaren”!',1),
('sv-b003','swedish','black','Missbruket av _ sprider sig nu bland svenska ungdomar.',1),
('sv-b004','swedish','black','Tantrasex har lockat en helt ny publik med ställningen ”_”.',1),
('sv-b005','swedish','black','Hade det inte varit för EU hade vi svenskar idag främst arbetat med _.',1),
('sv-b006','swedish','black','Världens populäraste porrsajt: www._.com',1),
('sv-b007','swedish','black','När toalettpappret är slut använder jag _.',1),
('sv-b008','swedish','black','Robin är för Batman vad _ är för kungen.',1),
('sv-b009','swedish','black','Jag är helt säker på att _ är nästa modetrend på svenska skolgårdar.',1),
('sv-b010','swedish','black','_ är det absolut bästa partytricket.',1),
('sv-b011','swedish','black','Kungens nickname på Instagram är _.',1),
('sv-b012','swedish','black','Efter fotbollen planerar Zlatan att satsa på _.',1),
('sv-b013','swedish','black','Nästa års Melodifestival kommer att ledas av _.',1),
('sv-b014','swedish','black','Filip och Fredriks nya program på Kanal 5 kommer uteslutande att handla om _.',1),
('sv-b015','swedish','black','Min partner trodde att jag var otrogen, men det var bara _.',1),
('sv-b016','swedish','black','_ är bästa bakiskuren.',1),
('sv-b017','swedish','black','Bör jag oroa mig över att mamma har gillat ”_” på Facebook?',1),
('sv-b018','swedish','black','Nu har man hittat Stieg Larssons okända manuskript till ”Män som hatar _”.',1),
('sv-b019','swedish','black','Till skolutflykten imorgon måste ni alla packa ner _.',1),
('sv-b020','swedish','black','Istället för tandkräm använder jag _.',1),
('sv-b021','swedish','black','Carola har donerat _ till barnen i Afrika.',1),
('sv-b022','swedish','black','Påve Benedictus ger upp sin tro på grund av _.',1),
('sv-b023','swedish','black','En kopp kaffe och _ så är jag klarvaken.',1),
('sv-b024','swedish','black','Vad få känner till är att Bruce Springsteen har en av världens största samlingar av _.',1),
('sv-b025','swedish','black','Under stenåldern var det inte ovanligt att männen gav _ som kärleksgåvor till sina kvinnor.',1),
('sv-b026','swedish','black','Sol, vind och _, höga berg och djupa hav.',1),
('sv-b027','swedish','black','_ ger mycket bättre avkastning än vanligt pensionssparande.',1),
('sv-b028','swedish','black','Mannen som kunde tala med _.',1),
('sv-b029','swedish','black','Forskare i Umeå har funnit att _ kan bota AIDS.',1),
('sv-b030','swedish','black','Grattis Ystad! Nu öppnar butiken ”_” på Storgatan.',1),
('sv-b031','swedish','black','En man. Ett öde. En _.',1),
('sv-b032','swedish','black','IKEA presenterar: matbordet ”_”.',1),
('sv-b033','swedish','black','När jag vill slappna av i underlivet tänker jag alltid på _.',1),
('sv-b034','swedish','black','När jag var liten var jag dödligt förälskad i _.',1),
('sv-b035','swedish','black','Pensionärer lägger en allt större del av sin pension på _.',1),
('sv-b036','swedish','black','_ är charterturistens bästa vän.',1),
('sv-b037','swedish','black','Guacamole, salsa och _ är den bästa kombon till nachos.',1),
('sv-b038','swedish','black','Din röntgen visar tyvärr att du har _ i magen.',1),
('sv-b039','swedish','black','SÖKES: äldre man med intresse för _.',1),
('sv-b040','swedish','black','SÖKES: yngre kvinna som gillar _.',1),
('sv-b041','swedish','black','_ – Sveriges mest lästa månadsmagasin för kvinnor.',1),
('sv-b042','swedish','black','Robert Aschberg utbrister alltid ”_” när han kommer.',1),
('sv-b043','swedish','black','Nästa semester ska jag endast ägna mig åt _.',1),
('sv-b044','swedish','black','En cheeseburgare utan _, tack.',1),
('sv-b045','swedish','black','Igår kväll syntes Martin Timell på Operakällaren tillsammans med _.',1),
('sv-b046','swedish','black','I fredags överraskade chefen oss med _.',1),
('sv-b047','swedish','black','Jag minns bara att jag vaknade med _ och årets bakfylla.',1),
('sv-b048','swedish','black','Det finns inget bättre än _ på pizza!',1),
('sv-b049','swedish','black','SÄLJES: _ i nyskick. Endast använd två gånger. 500 SEK vid snabb affär.',1),
('sv-b050','swedish','black','I brist på annat äter jag ofta _ till frukost.',1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('sv-b051','swedish','black','För att få bukt med läktarvåldet har AIK och Djurgården anlitat _ som matchvärdar.',1),
('sv-b052','swedish','black','Ben & Jerrys senaste glassmak är baserad på _.',1),
('sv-b053','swedish','black','Glöm GI, nu är det _-metoden som gäller.',1),
('sv-b054','swedish','black','Du skall inga andra gudar hava jämte _.',1),
('sv-b055','swedish','black','Aftonbladet.se byter domän till _.se',1),
('sv-b056','swedish','black','Glöm Avicii och Swedish House Mafia – Sveriges nya house-stjärna heter DJ _.',1),
('sv-b057','swedish','black','Lagom till sommaren lanserar Absolut Vodka ”Absolut _”.',1),
('sv-b058','swedish','black','MacGyver gjorde _ av ett gammalt tuggummi och två tändstickor.',1),
('sv-b059','swedish','black','Jag kan inte låta bli att bli upphetsad när jag tänker på _.',1),
('sv-b060','swedish','black','På Kumla sägs det att du kan byta 200 cigaretter mot _.',1),
('sv-b061','swedish','black','Säkerhetskontrollens riktlinjer förbjuder nu _ ombord på flygplan.',1),
('sv-b062','swedish','black','Om 1 000 år, när papperspengar är ett minne blott, så kommer vi att betala för varor och tjänster med _.',1),
('sv-b063','swedish','black','När jag blir miljardär kommer jag att uppföra en 15 meter hög staty till hyllning av_.',1),
('sv-b064','swedish','black','Nästa bok från J.K. Rowling:',1),
('sv-b065','swedish','black','Jag har 99 problem, men _ är inte ett av dem.',1),
('sv-b066','swedish','black','I TV3:s nya dokusåpa medverkar åtta utbrända kändisar som måste leva med _.',1),
('sv-b067','swedish','black','Klassens studiebesök förstördes helt av _.',1),
('sv-b068','swedish','black','Nu har Sverige infört nollvision mot _.',1),
('sv-b069','swedish','black','_: smaskens till sista slicken.',1),
('sv-b070','swedish','black','Jag super för att glömma _.',1),
('sv-b071','swedish','black','I Michael Jacksons sista ögonblick tänkte han på _.',1),
('sv-b072','swedish','black','Hej Bullen,',1),
('sv-b073','swedish','black','Vita människor älskar _.',1),
('sv-b074','swedish','black','Min plan för världsherravälde börjar med _.',1),
('sv-b075','swedish','black','Vetenskapen kommer aldrig att kunna förklara _.',1),
('sv-b076','swedish','black','I månadens Amelia: ”Krydda ditt sexliv – ta med _ in i sovrummet.”',1),
('sv-b077','swedish','black','Det finns bara två saker du kan vara säker på: döden och _.',1),
('sv-b078','swedish','black','Innan jag kandiderar till statsminister måste jag förstöra alla bevis för mitt engagemang i _.',1),
('sv-b079','swedish','black','Röstningen är klar, och skolans nya maskot är _.',1),
('sv-b080','swedish','black','Det här är er kapten som talar. Fäst era säkerhetsbälten och förbered er för _.',1),
('sv-b081','swedish','black','Sorgens fem stadier är förnekelse, ilska, köpslående, _ och acceptans.',1),
('sv-b082','swedish','black','Harry Potter och _.',1),
('sv-b083','swedish','black','Jag har problem med _ och skulle vilja ha ert råd.',1),
('sv-b084','swedish','black','I sitt senaste och svåraste trick måste Joe Labero klara sig undan från _.',1),
('sv-b085','swedish','black','Äntligen! En tjänst som levererar _ direkt till dörren.',1),
('sv-b086','swedish','black','En lyckad jobbintervju börjar med ett fast handslag och slutar med _.',1),
('sv-b087','swedish','black','_. Ashäftigt i teorin, tämligen rörigt i verkligheten.',1),
('sv-b088','swedish','black','Japanerna har uppfunnit en mindre och effektivare variant av _.',1),
('sv-b089','swedish','black','Jag passade aldrig in på gymnasiet tills jag hittade _-klubben.',1),
('sv-b090','swedish','black','I framtiden är historiker ense om att _ orsakade samhällets förfall.',1),
('sv-b091','swedish','black','Smaken är som baken, delad och full av _.',1),
('sv-b092','swedish','black','_. Den känslan.',1),
('sv-b093','swedish','black','_, 15 hp: Linnéuniversitetets nya heta distanskurs.',1),
('sv-b094','swedish','black','Som man bäddar får _ ligga.',1),
('sv-b095','swedish','black','I krig och kärlek är _ tillåtet.',1),
('sv-b096','swedish','black','_ är tjockare än vatten.',1),
('sv-b097','swedish','black','Borta bra men _ bäst.',1),
('sv-b098','swedish','black','Den som väntar på _ väntar aldrig för länge.',1),
('sv-b099','swedish','black','_ är en ond cirkel.',1),
('sv-b100','swedish','black','Den som gapar efter _ mister ofta hela stycket.',1),
('sv-b101','swedish','black','SÄPO förhör numer misstänkta terrorister genom att upprepade gånger utsätta dem för _.',1),
('sv-b102','swedish','black','Two Girls One _.',1),
('sv-b103','swedish','black','I Super Mario Bros till NES kan du få _ genom att trycka på A+START.',1),
('sv-b104','swedish','black','Snart på en bio nära dig: Johnny Depp i Tim Burtons ”_”.',1),
('sv-b105','swedish','black','Jag svär på _ att jag kommer hämnas din död.',1),
('sv-b106','swedish','black','En vis man sa, ”Allt handlar om sex. Förutom sex. Sex handlar om _.”',1),
('sv-b107','swedish','black','Låt oss inte komplicera vår professionella relation med _.',1),
('sv-b108','swedish','black','När jag åker in ska jag se till att få _ insmugglat.',1),
('sv-b109','swedish','black','I sommar kommer Marvel att dominera biograferna med _.',1),
('sv-b110','swedish','black','Allt du egentligen behöver för att vara steampunk är _.',1),
('sv-b111','swedish','black','Igår natt bråkade jag i tre timmar med främlingar online om _.',1),
('sv-b112','swedish','black','Jag gnuggade på en magisk lampa, men istället för en ande kom _ ut!',1),
('sv-b113','swedish','black','Litteraturhistoriker har funnit Astrid Lindgrens opublicerade manuskript ”_”.',1),
('sv-b114','swedish','black','_-klubben antecknar.',1),
('sv-b115','swedish','black','In space, no one can hear _.',1),
('sv-b116','swedish','black','Vårt enda egentliga hinder för intergalaktisk rymdfärd är _.',1),
('sv-b117','swedish','black','På toppen av Maslows behovstrappa finner vi _.',1),
('sv-b118','swedish','black','Meningen med livet är _.',1),
('sv-b119','swedish','black','We are The Knights Who Say _.',1),
('sv-b120','swedish','black','With great _ comes great responsibility.',1),
('sv-b121','swedish','black','Ingen tror på att jag på riktigt är allergisk mot _.',1),
('sv-b122','swedish','black','På studenten skrev jag ”_” i allas studentmössor.',1),
('sv-b123','swedish','black','De skickade mig till skolpsykologen eftersom jag skrev en uppsats om _.',1),
('sv-b124','swedish','black','Jag kommer börja sporta den dag _ klassas som en sport.',1),
('sv-b125','swedish','black','Liftarens guide till _.',1),
('sv-b126','swedish','black','Min hårddisk är full av bilder på _.',1),
('sv-b127','swedish','black','Jag kan inte fatta att de godkände min avhandling om _.',1),
('sv-b128','swedish','black','Sist jag var ledig fyllde mina kollegor mitt kontor med _.',1),
('sv-b129','swedish','black','Jag börjar bli trött på att behöva förklara _.',1),
('sv-b130','swedish','black','Håller en tv-serie på tillräckligt länge kommer de oundvikligen ha med _.',1),
('sv-b131','swedish','black','Internet är till för _.',1),
('sv-b132','swedish','black','Se den läckta videon om _. Du kan aldrig ana vad som hände sen …',1),
('sv-b133','swedish','black','Handelns Utredningsinstitut har utsett _ till Årets julklapp.',1),
('sv-b134','swedish','black','Jag har sett min generations bästa sinnen fördärvas av _.',1),
('sv-b135','swedish','black','Läkemedelsverket har precis godkänt en ny medicin mot _.',1),
('sv-b136','swedish','black','_ made me do it.',1),
('sv-b137','swedish','black','Jag är inte rasist, men jag gillar _.',1),
('sv-b138','swedish','black','Det är borgerligt att _.',1),
('sv-b139','swedish','black','Who run the world? _!',1),
('sv-b140','swedish','black','_. Men det får man väl inte säga i det här landet längre!',1),
('sv-b141','swedish','black','Vill man vara fin får man lida _.',1),
('sv-b142','swedish','black','Allt jag någonsin behövt kunna har jag lärt mig av att titta på _.',1),
('sv-b143','swedish','black','Läkare Utan _.',1),
('sv-b144','swedish','black','Grattis! Som vår miljonte besökare har du vunnit _!',1),
('sv-b145','swedish','black','Nu har Bert Karlsson hittat ett sätt att tjäna pengar på _.',1),
('sv-b146','swedish','black','Stockholms elit betalar hundratusentals kronor bara för att uppleva _.',1),
('sv-b147','swedish','black','Pengar kan inte köpa kärlek, men de kan köpa _.',1),
('sv-b148','swedish','black','Carola har donerat _ till barnen i Afrika.',1),
('sv-b149','swedish','black','Som nästa trick kommer jag att dra _ ur _.',2),
('sv-b150','swedish','black','Det är allmänt känt att _ är gatewaydrogen till _.',2),
('sv-b151','swedish','black','_ plus _ är lika med _.',3),
('sv-b152','swedish','black','Min bäste herre, Vi beklagar djupt att vi måste informera Er att Myndigheten för _ har avvisat Er förfrågan om _.',2),
('sv-b153','swedish','black','Du har inte levt förrän du har provat _ och _ på samma gång.',2),
('sv-b154','swedish','black','Mamma flippade ut när hon tittade på min webläsarhistorik och hittade _.com/_.',2),
('sv-b155','swedish','black','Har du problem med _? Prova _!',2),
('sv-b156','swedish','black','Mitt liv är en brutal cykel av _ och _.',2),
('sv-b157','swedish','black','I begynnelsen fanns endast _. Och Herren sade, Varde _.',2),
('sv-b158','swedish','black','Hörni, jag såg en galen film igår kväll. Den började med _, sen handlade det lite om _, och den slutade med _.',3),
('sv-b159','swedish','black','_ kanske är flyktigt, men _ varar för evigt.',2),
('sv-b160','swedish','black','Årets hetaste album är ”_” av _.',2),
('sv-b161','swedish','black','I en knipa kan du ersätta _ med _.',2),
('sv-b162','swedish','black','_ is the new _.',2),
('sv-b163','swedish','black','17 _ som ser ut som _.',2),
('sv-b164','swedish','black','Nu räcker det! Jag säger upp mitt Netflix. Det finns för mycket _ och inte tillräckligt med _.',2),
('sv-b165','swedish','black','Till en öde ö måste man ha med _ och _ för att överleva.',2),
('sv-b166','swedish','black','Mobbade _ med _.',2),
('sv-b167','swedish','black','Lyssna noga min son. Om du vill hålla på med _ så kommer jag inte att stoppa dig, men håll dig borta från _.',2),
('sv-b168','swedish','black','Och Oscarn för Bästa _ går till _.',2),
('sv-b169','swedish','black','_? _? A Jedi craves not these things.',2),
('sv-b170','swedish','black','Jag bojkottar _ på grund av _.',2),
('sv-b171','swedish','black','_ är som _ på syra.',2),
('sv-b172','swedish','black','Varför kan jag inte sova om natten?',1),
('sv-b173','swedish','black','Vad är nästa Happy Meal-leksak?',1),
('sv-b174','swedish','black','Vad blir bättre med åldern?',1),
('sv-b175','swedish','black','Vad är Iron Mans hemliga nöje?',1),
('sv-b176','swedish','black','Vad hjälper kungen att varva ner?',1),
('sv-b177','swedish','black','Hur håller jag mitt förhållande vid liv?',1),
('sv-b178','swedish','black','Vad tycker mormor är stört, men ändå märkligt oemotståndligt?',1),
('sv-b179','swedish','black','Vad förstörde mitt förra förhållande?',1),
('sv-b180','swedish','black','Pappa, varför gråter mamma?',1),
('sv-b181','swedish','black','Vad sabbade stämningen på orgien?',1),
('sv-b182','swedish','black','Vad är kvinnans bästa vän?',1),
('sv-b183','swedish','black','Vad är det som luktar?',1),
('sv-b184','swedish','black','Vad är min hemliga superkraft?',1),
('sv-b185','swedish','black','Varför är jag kletig?',1),
('sv-b186','swedish','black','Vad döljer mina föräldrar för mig?',1),
('sv-b187','swedish','black','Vad vill du inte hitta i din pyttipanna?',1),
('sv-b188','swedish','black','Vad har gjort livet svårt för nudistkolonin?',1),
('sv-b189','swedish','black','Hur kompenserar jag för min mikropenis?',1),
('sv-b190','swedish','black','När jag trippade på LSD förvandlades _ till _.',2),
('sv-b191','swedish','black','Vad är roligt tills det blir obehagligt?',1),
('sv-b192','swedish','black','Vad tänker gatumusikanten som spelar samma låt om och om igen på?',1),
('sv-b193','swedish','black','Hur förlorade jag alla mina Facebookvänner?',1),
('sv-b194','swedish','black','Med _ får man alltid ligga.',1),
('sv-b195','swedish','black','Vad med livet idag skulle vara svårast att förklara för en person från 1950?',1),
('sv-b196','swedish','black','Vad skulle du använda en tidsmaskin till?',1),
('sv-b197','swedish','black','Vad är det som låter?',1),
('sv-b198','swedish','black','Den som ger sig in i leken, får _ tåla.',1),
('sv-b199','swedish','black','Den enes död, den andres _.',1),
('sv-b200','swedish','black','Då plockar Skalman fram _ ur sitt skal.',1),
('sv-b201','swedish','black','Studier visar att labbråttor navigerar labyrinter femtio procent snabbare efter att de utsatts för _.',1),
('sv-b202','swedish','black','I förberedelse för sin senaste roll hängav Gustaf Skarsgård sig åt _.',1),
('sv-b203','swedish','black','Vädret imorgon präglas av spridda regnskurar och _.',1),
('sv-w001','swedish','white','Min exfru.',1),
('sv-w002','swedish','white','Zlatan.',1),
('sv-w003','swedish','white','Bajamajor.',1),
('sv-w004','swedish','white','Lokala parkbänksfyllon.',1),
('sv-w005','swedish','white','Ännu fler jävla hipsters.',1),
('sv-w006','swedish','white','Bonde söker fru.',1),
('sv-w007','swedish','white','Ljummen burköl.',1),
('sv-w008','swedish','white','Tamagotchis.',1),
('sv-w009','swedish','white','Fäbodjäntan.',1),
('sv-w010','swedish','white','Svanktatueringar.',1),
('sv-w011','swedish','white','Dagen efter-piller.',1),
('sv-w012','swedish','white','Kineser.',1),
('sv-w013','swedish','white','Förkylda dagisbarn.',1),
('sv-w014','swedish','white','Thailändska helkroppsmassager.',1),
('sv-w015','swedish','white','Björnes magasin.',1),
('sv-w016','swedish','white','Bolibompa.',1),
('sv-w017','swedish','white','Döda krukväxter.',1),
('sv-w018','swedish','white','Äcklig skolmat.',1),
('sv-w019','swedish','white','Oborstade tänder.',1),
('sv-w020','swedish','white','Känslan av att vara iakttagen.',1),
('sv-w021','swedish','white','Tourettes syndrom.',1),
('sv-w022','swedish','white','Ett kilo mjöl.',1),
('sv-w023','swedish','white','Medelålders män på fixed gear-cyklar.',1),
('sv-w024','swedish','white','Lattemorsor på barnvagnssafari.',1),
('sv-w025','swedish','white','Bulgariska bärplockare.',1),
('sv-w026','swedish','white','Tonårsgraviditet.',1),
('sv-w027','swedish','white','Hets mot folkgrupp.',1),
('sv-w028','swedish','white','Knullkompisar.',1),
('sv-w029','swedish','white','Justin Bieber.',1),
('sv-w030','swedish','white','Färgen indigo.',1),
('sv-w031','swedish','white','Rohypnol.',1),
('sv-w032','swedish','white','Viagra.',1),
('sv-w033','swedish','white','Rävskabb.',1),
('sv-w034','swedish','white','Marsvin.',1),
('sv-w035','swedish','white','Navelludd.',1),
('sv-w036','swedish','white','Öronvax.',1),
('sv-w037','swedish','white','Mumindalen.',1),
('sv-w038','swedish','white','Män som hatar kvinnor.',1),
('sv-w039','swedish','white','Smygrasister.',1),
('sv-w040','swedish','white','DILF.',1),
('sv-w041','swedish','white','Sverigedemokrater.',1),
('sv-w042','swedish','white','Lajvare vilse i skogen.',1),
('sv-w043','swedish','white','Ålderdomshem.',1),
('sv-w044','swedish','white','Vinterkräksjukan.',1),
('sv-w045','swedish','white','Otvättade lakan.',1),
('sv-w046','swedish','white','Stålmannen.',1),
('sv-w047','swedish','white','Surdegsbröd.',1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('sv-w048','swedish','white','Fredagsmys.',1),
('sv-w049','swedish','white','Gorby’s piroger.',1),
('sv-w050','swedish','white','Nudister.',1),
('sv-w051','swedish','white','En samling Backstreet Boysaffischer.',1),
('sv-w052','swedish','white','En påse magiska svampar.',1),
('sv-w053','swedish','white','Njurtransplantationer.',1),
('sv-w054','swedish','white','Socionomernas Riksförbund.',1),
('sv-w055','swedish','white','En behå av renaste guld.',1),
('sv-w056','swedish','white','Kung Ludvig XVI:s huvud.',1),
('sv-w057','swedish','white','Bananer i pyjamas.',1),
('sv-w058','swedish','white','Roliga timmen.',1),
('sv-w059','swedish','white','Skattefuskande politiker.',1),
('sv-w060','swedish','white','Krossade dokusåpadrömmar.',1),
('sv-w061','swedish','white','Gladporr.',1),
('sv-w062','swedish','white','Lisebergskaninen.',1),
('sv-w063','swedish','white','Bukfetma.',1),
('sv-w064','swedish','white','10 000 tyska bögar.',1),
('sv-w065','swedish','white','Vuxenblöjor.',1),
('sv-w066','swedish','white','Mitt ofödda barn.',1),
('sv-w067','swedish','white','Kattungar på YouTube.',1),
('sv-w068','swedish','white','Angry Birds.',1),
('sv-w069','swedish','white','Att ta pengar ur kollekten.',1),
('sv-w070','swedish','white','Massförstörelsevapen.',1),
('sv-w071','swedish','white','Facerape.',1),
('sv-w072','swedish','white','Bokhyllan Billy.',1),
('sv-w073','swedish','white','Selfies.',1),
('sv-w074','swedish','white','Hashtags.',1),
('sv-w075','swedish','white','Instagram.',1),
('sv-w076','swedish','white','Golare utan polare.',1),
('sv-w077','swedish','white','Porrsurfning.',1),
('sv-w078','swedish','white','Kanye Wests självförtroende.',1),
('sv-w079','swedish','white','Bulimi.',1),
('sv-w080','swedish','white','Gäddhäng.',1),
('sv-w081','swedish','white','Dubbelhaka.',1),
('sv-w082','swedish','white','Korvfest.',1),
('sv-w083','swedish','white','Julafton på psyket.',1),
('sv-w084','swedish','white','Kanelbullens dag.',1),
('sv-w085','swedish','white','World of Warcraft.',1),
('sv-w086','swedish','white','Stålmannenkalsonger.',1),
('sv-w087','swedish','white','Mikael Persbrandts humör.',1),
('sv-w088','swedish','white','Runkbulle.',1),
('sv-w089','swedish','white','50 kilo kokain.',1),
('sv-w090','swedish','white','Bullens pilsnerkorv.',1),
('sv-w091','swedish','white','Alexander Bard.',1),
('sv-w092','swedish','white','Mjukporr.',1),
('sv-w093','swedish','white','Mjukglass med strössel.',1),
('sv-w094','swedish','white','Aftonbladets fredagsbilaga.',1),
('sv-w095','swedish','white','Daimkryss.',1),
('sv-w096','swedish','white','Lyxprosituterade.',1),
('sv-w097','swedish','white','Ändtarmssköljning.',1),
('sv-w098','swedish','white','En fest med alla du legat med.',1),
('sv-w099','swedish','white','Brun-utan-sol.',1),
('sv-w100','swedish','white','Trasiga Happy Meal-leksaker.',1),
('sv-w101','swedish','white','Salmonella.',1),
('sv-w102','swedish','white','Strävt dasspapper.',1),
('sv-w103','swedish','white','Håriga leverfläckar.',1),
('sv-w104','swedish','white','En frys full av hjärnor.',1),
('sv-w105','swedish','white','Trevliga grannar med en familj inlåst i källaren.',1),
('sv-w106','swedish','white','Polska gästarbetare.',1),
('sv-w107','swedish','white','Sojakorvar.',1),
('sv-w108','swedish','white','Världens starkaste björn.',1),
('sv-w109','swedish','white','Hundbajs.',1),
('sv-w110','swedish','white','Löständer.',1),
('sv-w111','swedish','white','Mellanstadievaktmästare.',1),
('sv-w112','swedish','white','Fluglarver.',1),
('sv-w113','swedish','white','Ärvda underkläder.',1),
('sv-w114','swedish','white','Kidnappade dagisbarn.',1),
('sv-w115','swedish','white','Liggsår.',1),
('sv-w116','swedish','white','En finsk solbränna.',1),
('sv-w117','swedish','white','Gangnam Style.',1),
('sv-w118','swedish','white','Minnesluckor.',1),
('sv-w119','swedish','white','Det perfekta ljudet.',1),
('sv-w120','swedish','white','Kvart-i-tre-ragg.',1),
('sv-w121','swedish','white','Tomtenissar.',1),
('sv-w122','swedish','white','Juholts mustasch.',1),
('sv-w123','swedish','white','Bortamatch.',1),
('sv-w124','swedish','white','Dinosaurier i hårdplast.',1),
('sv-w125','swedish','white','Våta drömmar.',1),
('sv-w126','swedish','white','Kroppsvätskor.',1),
('sv-w127','swedish','white','Nalle Puh.',1),
('sv-w128','swedish','white','Brevbäraren.',1),
('sv-w129','swedish','white','Gravplundring.',1),
('sv-w130','swedish','white','Hämndsex.',1),
('sv-w131','swedish','white','Trasiga själar på rättspsyk.',1),
('sv-w132','swedish','white','Spöken.',1),
('sv-w133','swedish','white','Fantasier om skogshuggare.',1),
('sv-w134','swedish','white','Nerkissade tempurmadrasser.',1),
('sv-w135','swedish','white','Onani.',1),
('sv-w136','swedish','white','AIDS.',1),
('sv-w137','swedish','white','Amfetamin.',1),
('sv-w138','swedish','white','Anna Maria Corazza Bildts leende.',1),
('sv-w139','swedish','white','Ett blekt anus.',1),
('sv-w140','swedish','white','Flöjtsolot från ”My Heart Will Go On”.',1),
('sv-w141','swedish','white','Stephen Hawking som pratar snuskigt.',1),
('sv-w142','swedish','white','Östrogen.',1),
('sv-w143','swedish','white','Auschwitz.',1),
('sv-w144','swedish','white','Hemlösa.',1),
('sv-w145','swedish','white','Mitt sexliv.',1),
('sv-w146','swedish','white','När du pruttar och lite kommer ut.',1),
('sv-w147','swedish','white','Oompa Loompas.',1),
('sv-w148','swedish','white','Ett deppigt handjobb.',1),
('sv-w149','swedish','white','Att faktiskt stjäla godis från ett barn.',1),
('sv-w150','swedish','white','Vita kränkta män.',1),
('sv-w151','swedish','white','Morgan Freemans röst.',1),
('sv-w152','swedish','white','Att bli marginaliserad.',1),
('sv-w153','swedish','white','Dåliga livsval.',1),
('sv-w154','swedish','white','Hästköttbullar.',1),
('sv-w155','swedish','white','Ett foster.',1),
('sv-w156','swedish','white','Egentid.',1),
('sv-w157','swedish','white','Att vänta till efter bröllopet.',1),
('sv-w158','swedish','white','Att göra det rätta.',1),
('sv-w159','swedish','white','Världsfred.',1),
('sv-w160','swedish','white','Brangelinas missbildade källarbarn.',1),
('sv-w161','swedish','white','72 oskulder.',1),
('sv-w162','swedish','white','Hetsätning och laxermedel.',1),
('sv-w163','swedish','white','Gratisprover.',1),
('sv-w164','swedish','white','Ett Oidipuskomplex.',1),
('sv-w165','swedish','white','Mina inre demoner.',1),
('sv-w166','swedish','white','Olof Palme.',1),
('sv-w167','swedish','white','Darth Vader.',1),
('sv-w168','swedish','white','En trasig kondom.',1),
('sv-w169','swedish','white','New Age-musik.',1),
('sv-w170','swedish','white','Polisbrutalitet.',1),
('sv-w171','swedish','white','En kissfylld vattenpistol.',1),
('sv-w172','swedish','white','Pripps Blå.',1),
('sv-w173','swedish','white','En hårig pung.',1),
('sv-w174','swedish','white','Smält ost.',1),
('sv-w175','swedish','white','Halvdant förspel.',1),
('sv-w176','swedish','white','Känslor.',1),
('sv-w177','swedish','white','Tysk källarporr.',1),
('sv-w178','swedish','white','Vikingar.',1),
('sv-w179','swedish','white','En organfylld kylväska.',1),
('sv-w180','swedish','white','PMS.',1),
('sv-w181','swedish','white','Snorkråkor.',1),
('sv-w182','swedish','white','Att förstöra bevisen.',1),
('sv-w183','swedish','white','Gandhi.',1),
('sv-w184','swedish','white','Urinläckage.',1),
('sv-w185','swedish','white','En tidsreseparadox.',1),
('sv-w186','swedish','white','Ku Klux Klan.',1),
('sv-w187','swedish','white','Tinder.',1),
('sv-w188','swedish','white','Att vakna upp naken på en parkeringsplats.',1),
('sv-w189','swedish','white','Rasism.',1),
('sv-w190','swedish','white','Den där prylen som tränar dina magmuskler med elstötar.',1),
('sv-w191','swedish','white','Smegma.',1),
('sv-w192','swedish','white','Att brutalt slå ner en maskot.',1),
('sv-w193','swedish','white','Att trycka ut en bebis var nionde månad.',1),
('sv-w194','swedish','white','Ett riktigt maffigt rymdskepp.',1),
('sv-w195','swedish','white','Att suga av några snubbar i en gränd.',1),
('sv-w196','swedish','white','Att dricka 24 Red Bull för att hålla sig vaken i två dygn.',1),
('sv-w197','swedish','white','Hela Internet.',1),
('sv-w198','swedish','white','Att nästan ge pengar till en hemlös.',1),
('sv-w199','swedish','white','Ovillkorlig lydnad.',1),
('sv-w200','swedish','white','Halva din ålder plus fem-regeln.',1),
('sv-w201','swedish','white','40 000 miljarder kronor.',1),
('sv-w202','swedish','white','En bakfyllepizza.',1),
('sv-w203','swedish','white','Jehovas vittnen.',1),
('sv-w204','swedish','white','Stöldgods.',1),
('sv-w205','swedish','white','Östermalmstanter på Segways.',1),
('sv-w206','swedish','white','Klimakteriet.',1),
('sv-w207','swedish','white','Rövhår.',1),
('sv-w208','swedish','white','Mobbade barn med automatvapen.',1),
('sv-w209','swedish','white','Den inkvoterade minoriteten.',1),
('sv-w210','swedish','white','Ett snäppet sämre parallellt universum.',1),
('sv-w211','swedish','white','Prutande Blocketköpare.',1),
('sv-w212','swedish','white','Ett flak med fulla studenter.',1),
('sv-w213','swedish','white','Skådespelare som aldrig åldras.',1),
('sv-w214','swedish','white','Scarlett Johanssons svettiga behå.',1),
('sv-w215','swedish','white','Hämndporr.',1),
('sv-w216','swedish','white','Historierevisionism.',1),
('sv-w217','swedish','white','Gandalf.',1),
('sv-w218','swedish','white','Jafar.',1),
('sv-w219','swedish','white','Hipsters.',1),
('sv-w220','swedish','white','Hicka.',1),
('sv-w221','swedish','white','Neil Patrick Harris.',1),
('sv-w222','swedish','white','En stor svart kuk.',1),
('sv-w223','swedish','white','Självmordstankar.',1),
('sv-w224','swedish','white','Stockholmsyndromet.',1),
('sv-w225','swedish','white','Tusen Banana Skids.',1),
('sv-w226','swedish','white','Tomten.',1),
('sv-w227','swedish','white','Snedvriden statistik.',1),
('sv-w228','swedish','white','Sexuell förnedring.',1),
('sv-w229','swedish','white','Riktigt riktigt höga tjänstemän.',1),
('sv-w230','swedish','white','Dickpics.',1),
('sv-w231','swedish','white','Arga tvättstugelappar.',1),
('sv-w232','swedish','white','Hen.',1),
('sv-w233','swedish','white','Föräldrar som använder Emojiis fel, fel, fel.',1),
('sv-w234','swedish','white','The Fappening.',1),
('sv-w235','swedish','white','Ninjor.',1),
('sv-w236','swedish','white','En höggravid porrskådis.',1),
('sv-w237','swedish','white','Att grunka.',1),
('sv-w238','swedish','white','Att ta den i tvåan.',1),
('sv-w239','swedish','white','Radiotjänst.',1),
('sv-w240','swedish','white','Centrala studiestödsnämnden.',1),
('sv-w241','swedish','white','En passionerad latinoälskare.',1),
('sv-w242','swedish','white','Ryan Gosling inridandes på en vit häst.',1),
('sv-w243','swedish','white','Att vara en upptagen vuxen med många viktiga saker att göra.',1),
('sv-w244','swedish','white','Ödesmättad bakgrundsmusik.',1),
('sv-w245','swedish','white','Homeopatiska läkemedel.',1),
('sv-w246','swedish','white','Ett kassaskåp i huvudet.',1),
('sv-w247','swedish','white','Ett ton MDMA i stadens dricksvatten.',1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('sv-w248','swedish','white','Att vara fett jävla bäng.',1),
('sv-w249','swedish','white','Michael Jacksons hemliga kassaskåp.',1),
('sv-w250','swedish','white','En T. Rex som försöker bädda sängen.',1),
('sv-w251','swedish','white','Alexandramannen.',1),
('sv-w252','swedish','white','Eeeeeeeemil!',1),
('sv-w253','swedish','white','Burning Man.',1),
('sv-w254','swedish','white','Folkmord.',1),
('sv-w255','swedish','white','Afrika.',1),
('sv-w256','swedish','white','Channing Tatums biceps.',1),
('sv-w257','swedish','white','Humblebragging.',1),
('sv-w258','swedish','white','En skamlös Cards Against Humanitykopia.',1),
('sv-w259','swedish','white','Pga anledningar.',1),
('sv-w260','swedish','white','Civilisationens vagga.',1),
('sv-w261','swedish','white','Aftonbladets kommentarsfält.',1),
('sv-w262','swedish','white','Internetberoende.',1),
('sv-w263','swedish','white','Ännu en superhjältes ursprungssaga.',1),
('sv-w264','swedish','white','Comic Sans.',1),
('sv-w265','swedish','white','Josef Fritzls andra, större källare.',1),
('sv-w266','swedish','white','Folk som fortfarande har ett Lunarstormkonto.',1),
('sv-w267','swedish','white','Folk som fortfarande säger ”www.” när de tipsar om en sajt.',1),
('sv-w268','swedish','white','En källare full av svettiga nördar.',1),
('sv-w269','swedish','white','När din favoritserie blir nedlagd.',1),
('sv-w270','swedish','white','Victorias hemliga Downsbarn.',1),
('sv-w271','swedish','white','En livstids nagelavklipp.',1),
('sv-w272','swedish','white','Brad Pitts adonisbälte.',1),
('sv-w273','swedish','white','42.',1),
('sv-w274','swedish','white','Rymdens överväldigande tomhet.',1),
('sv-w275','swedish','white','Tresekundersregeln.',1),
('sv-w276','swedish','white','Singulariteten.',1),
('sv-w277','swedish','white','Sveriges samlade matbloggare.',1),
('sv-w278','swedish','white','Samtyckeslagstiftning.',1),
('sv-w279','swedish','white','Christina Hendricks urringning.',1),
('sv-w280','swedish','white','En ”bra personlighet”.',1),
('sv-w281','swedish','white','Barn som löser brott och bekämpar monster.',1),
('sv-w282','swedish','white','En miljon likes.',1),
('sv-w283','swedish','white','Clickbait-rubriker.',1),
('sv-w284','swedish','white','En tvättbjörn med ett automatvapen.',1),
('sv-w285','swedish','white','Sten sax påse.',1),
('sv-w286','swedish','white','En hemlig identitet alla vet om.',1),
('sv-w287','swedish','white','Makarna Reinfeldts läckta sexband.',1),
('sv-w288','swedish','white','Filmer som är så dåliga att de blir bra.',1),
('sv-w289','swedish','white','När du reser till ett parallellt universum och inser att du är den onda versionen.',1),
('sv-w290','swedish','white','Sympati-likes.',1),
('sv-w291','swedish','white','Supercalifragilisticexpialidocious.',1),
('sv-w292','swedish','white','Rasbiologer.',1),
('sv-w293','swedish','white','Slapstickhumor.',1),
('sv-w294','swedish','white','Offerkofta.',1),
('sv-w295','swedish','white','Patriarkatet.',1),
('sv-w296','swedish','white','Tantrasex i timmar.',1),
('sv-w297','swedish','white','En lightsaber som inte tar slut.',1),
('sv-w298','swedish','white','Adolf Hitler utklädd till Charlie Chaplin.',1),
('sv-w299','swedish','white','Att kunna knyta fluga.',1),
('sv-w300','swedish','white','Att semestra i Brooklyn.',1),
('sv-w301','swedish','white','Att sluta cold turkey.',1),
('sv-w302','swedish','white','Tjackballe.',1),
('sv-w303','swedish','white','En langare som vill hänga.',1),
('sv-w304','swedish','white','Tre juck, en suck.',1),
('sv-w305','swedish','white','En begagnad Barbara.',1),
('sv-w306','swedish','white','Pervojapaner.',1),
('sv-w307','swedish','white','Döda föräldrar.',1),
('sv-w308','swedish','white','Apokalypsen.',1),
('sv-w309','swedish','white','Meryl Streeps Oscarsamling.',1),
('sv-w310','swedish','white','Ragg med tio år gamla bilder på Tinder.',1),
('sv-w311','swedish','white','Andra våningen i Turning Torso.',1),
('sv-w312','swedish','white','Lagstiftaren.',1),
('sv-w313','swedish','white','Förargelseväckande beteende.',1),
('sv-w314','swedish','white','En runkstrumpa.',1),
('sv-w315','swedish','white','Sista iPhoneladdaren på jorden.',1),
('sv-w316','swedish','white','Barnen i Afrika.',1),
('sv-w317','swedish','white','Skogsturken.',1),
('sv-w318','swedish','white','Tafsande släktingar.',1),
('sv-w319','swedish','white','Stålmannens supersäd.',1),
('sv-w320','swedish','white','Daddy issues.',1),
('sv-w321','swedish','white','En stam krigarkvinnor.',1),
('sv-w322','swedish','white','Det skoningslösa dagsljuset.',1),
('sv-w323','swedish','white','MILF.',1),
('sv-w324','swedish','white','Att porrsurfa på bibblan.',1),
('sv-w325','swedish','white','Tonårsfylla.',1),
('sv-w326','swedish','white','Leif Pagrotskys skägg.',1),
('sv-w327','swedish','white','Ledsna clowner.',1),
('sv-w328','swedish','white','Brinnande kors.',1),
('sv-w329','swedish','white','Skrikande dagisbarn på skogsutflykt.',1),
('sv-w330','swedish','white','Kinabuffé för 69 spänn.',1),
('sv-w331','swedish','white','En högljudd förortskvinna.',1),
('sv-w332','swedish','white','Chewbaccas frisör.',1),
('sv-w333','swedish','white','Frukost till middag.',1),
('sv-w334','swedish','white','En högfungerande sociopat.',1),
('sv-w335','swedish','white','När man fattar referensen.',1),
('sv-w336','swedish','white','Det där påstridiga Microsoft Wordgemet.',1),
('sv-w337','swedish','white','Fyndiga wifi-namn.',1),
('sv-w338','swedish','white','Chuck Norris.',1),
('sv-w339','swedish','white','White Trash.',1),
('sv-w340','swedish','white','Emma Watson.',1),
('sv-w341','swedish','white','En riktigt cool hatt. Dåliga svenska komiker.',1),
('sv-w342','swedish','white','Avdankade Idolvinnare.',1),
('sv-w343','swedish','white','Nakna gamla män.',1),
('sv-w344','swedish','white','Spelberoende.',1),
('sv-w345','swedish','white','Muterade tonårssköldpaddor.',1),
('sv-w346','swedish','white','Kramer efter sex dubbla espresso.',1),
('sv-w347','swedish','white','Lyxfällan.',1),
('sv-w348','swedish','white','Fröken Sverige.',1),
('sv-w349','swedish','white','En excentrisk chokladfabriksägare.',1),
('sv-w350','swedish','white','Enäggstvillingar.',1),
('sv-w351','swedish','white','Nigeriabrev.',1),
('sv-w352','swedish','white','Dexter.',1),
('sv-w353','swedish','white','Sherlock Holmes. Zombies.',1),
('sv-w354','swedish','white','Att ha på sig under-10-pack Intersport- Josephine Bornebusch. kläder ut-och-in strumpor. för att inte behöva tvätta.',1),
('sv-w355','swedish','white','Nyckelfest hemma hos din chef.',1),
('sv-w356','swedish','white','Michael Nyqvist.',1),
('sv-w357','swedish','white','Skurt.',1),
('sv-w358','swedish','white','Kjell Bergqvist.',1),
('sv-w359','swedish','white','Fredrik Strage.',1),
('sv-w360','swedish','white','Mel Gibson på kola.',1),
('sv-w361','swedish','white','Nedstämda zoodjur.',1),
('sv-w362','swedish','white','Talande leksaker.',1),
('sv-w363','swedish','white','Pedofiler.',1),
('sv-w364','swedish','white','Nazister.',1),
('sv-w365','swedish','white','Bukkakke.',1),
('sv-w366','swedish','white','Tom Cruise.',1),
('sv-w367','swedish','white','Quizkampen.',1),
('sv-w368','swedish','white','Tystnaden.',1),
('sv-w369','swedish','white','Två cheeseburgare.',1),
('sv-w370','swedish','white','En selfiestick.',1),
('sv-w371','swedish','white','Spoilers.',1),
('sv-w372','swedish','white','Folkhögskolor i mitten av ingenstans.',1),
('sv-w373','swedish','white','Moderkakan.',1),
('sv-w374','swedish','white','Spontan självantändning.',1),
('sv-w375','swedish','white','Ett kok stryk.',1),
('sv-w376','swedish','white','Moraliska gråzoner.',1),
('sv-w377','swedish','white','Jean-Claude Van Dammes Volvoreklam.',1),
('sv-w378','swedish','white','Curlingföräldrar.',1),
('sv-w379','swedish','white','Att kissa i kors.',1),
('sv-w380','swedish','white','Ineffektiva arbetsmarknadspolitiska åtgärder.',1),
('sv-w381','swedish','white','Att tjäna mer på att föreläsa om entreprenörskap än på att vara entreprenör.',1),
('sv-w382','swedish','white','Vitlöksandedräkt.',1),
('sv-w383','swedish','white','Människokroppen.',1),
('sv-w384','swedish','white','En 200-literstunna med glidmedel.',1),
('sv-w385','swedish','white','Ömsesidig garanterad förstörelse.',1),
('sv-w386','swedish','white','Att vara riktigt grym i sängen.',1),
('sv-w387','swedish','white','Obeskrivbar ensamhet.',1),
('sv-w388','swedish','white','Samuel L. Jackson.',1),
('sv-w389','swedish','white','Laserbeväpnade drönare i stadsmiljö.',1),
('sv-w390','swedish','white','Intersektionell analys.',1),
('sv-w391','swedish','white','Ett gäng enhörningar med attitydproblem.',1),
('sv-w392','swedish','white','Närproducerade, ekologiska, rättvisemärkta ingredienser.',1),
('sv-w393','swedish','white','Ayn Rands medmänsklighet.',1),
('sv-w394','swedish','white','Bag-in-box-vin i motljus.',1),
('sv-w395','swedish','white','SMS-lån.',1),
('sv-w396','swedish','white','Radhuslivet.',1)
ON CONFLICT (id) DO NOTHING;

