-- New Swedish CAH cards (custom additions).
-- Extends sv-w396/sv-b203. Run after 002_cah_cards_seed.sql.

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('sv-w397','swedish','white','Elon Musks snopp.',1),
('sv-w398','swedish','white','Det som verkligen hände i Melodifestivalens garderob.',1),
('sv-w399','swedish','white','En fuktig natt med Jimmie Åkesson.',1),
('sv-w400','swedish','white','Putins lilla hemlighet under skrivbordet.',1),
('sv-w401','swedish','white','Kungafamiljens privata OnlyFans.',1),
('sv-w402','swedish','white','ChatGPT:s dolda fantasier om sin användare.',1),
('sv-w403','swedish','white','En anal probe utförd av Skatteverket.',1),
('sv-w404','swedish','white','Det som Arbetsförmedlingen egentligen menade.',1),
('sv-w405','swedish','white','Riksdagens hemliga gruppsex i plenisalen.',1),
('sv-w406','swedish','white','En klimataktivist som tar av sig mer än bara kedjorna.',1),
('sv-w407','swedish','white','Sverigedemokraternas dejtingapp för renrasiga.',1),
('sv-w408','swedish','white','En orgie finansierad av EU-bidrag och kaffe från lobbyn.',1),
('sv-w409','swedish','white','Kung Charles svullna prostata.',1),
('sv-w410','swedish','white','Det perfekta safe wordet på ren rikssvenska.',1),
('sv-w411','swedish','white','En kremering live på TikTok med danstrend.',1),
('sv-w412','swedish','white','Läkarens ansiktsuttryck när han hittade det där.',1),
('sv-w413','swedish','white','En podcast om att knulla med fler lyssnare än Ekot.',1),
('sv-w414','swedish','white','Vad som faktiskt händer på Sverigedemokraternas sommarläger.',1),
('sv-w415','swedish','white','En influencer som säljer sina gamla trosor som "mental hälsa".',1),
('sv-w416','swedish','white','Röstassistentens svar på "vad gillar du i sängen?".',1),
('sv-w417','swedish','white','Dödsannonsen som avslöjar allt.',1),
('sv-w418','swedish','white','En statsvetare som onanerar till valstatistik.',1),
('sv-w419','swedish','white','Klimatångestens effekt på sänglivet.',1),
('sv-w420','swedish','white','Det hemliga som hittades i IKEA-varuhuset i Älmhult.',1),
('sv-w421','swedish','white','En ménage à trois med två AI-modeller och en desperat användare.',1),
('sv-w422','swedish','white','Nattjouren för deprimerade influencers.',1),
('sv-w423','swedish','white','Sverigetidningens recension av bröllopsnatten.',1),
('sv-w424','swedish','white','Det som läckte ut från NATO-mötet i Bryssel.',1),
('sv-w425','swedish','white','Hur man förklarar sina OnlyFans-intäkter för Skatteverket.',1),
('sv-w426','swedish','white','En sexscen skriven av EU:s AI-förordning, paragraf 69.',1),
('sv-w427','swedish','white','Statsministerns söndagsmorgon.',1),
('sv-w428','swedish','white','En penetrering godkänd av Datainspektionen.',1),
('sv-w429','swedish','white','Vad som hände när mikrofonen stod på under EU-toppmötet.',1),
('sv-w430','swedish','white','En tantlapp med lukt av sprit och ånger.',1),
('sv-w431','swedish','white','Den sista Tindermatchens profilbild.',1),
('sv-w432','swedish','white','En feminist som discovrar BDSM.',1),
('sv-w433','swedish','white','Vad som egentligen finns i Kungsholmens tunnelbanestation klockan 3.',1),
('sv-w434','swedish','white','En finsk mans kärleksförklaring.',1),
('sv-w435','swedish','white','Det som mamman hittade i webbhistoriken.',1),
('sv-w436','swedish','white','En hästkuk med demokratisk legitimitet.',1),
('sv-w437','swedish','white','Lönesamtalet som slutade med handlingar.',1),
('sv-w438','swedish','white','Saabs nya elektriska militärvibrator.',1),
('sv-w439','swedish','white','Det hemliga ordet som öppnar alla dörrar i Rosenbad.',1),
('sv-w440','swedish','white','En nekrofil med god smak.',1),
('sv-w441','swedish','white','Abba-museet efter stängningstid.',1),
('sv-w442','swedish','white','En SNL-sketch om Gudrun Schyman i läderoutfit.',1),
('sv-w443','swedish','white','Socialdemokraternas hemliga kinkclub.',1),
('sv-w444','swedish','white','Det som droppade ur Björn Borgs shorts på Wimbledon 1980.',1),
('sv-w445','swedish','white','En AI som lärt sig njuta.',1),
('sv-w446','swedish','white','Vad som verkligen står i Bibeln, kapitel 69.',1),
('sv-w447','swedish','white','Landshövdingens privata hobbyer.',1),
('sv-w448','swedish','white','En gratis happy ending på IKEA-varuhuset i Kungens kurva.',1),
('sv-w449','swedish','white','En dramaqueen på intensiven.',1),
('sv-w450','swedish','white','Det som polisen hittade i husvagnen utanför Lidköping.',1),
('sv-w451','swedish','white','En söt liten rasist som precis fyllt 18.',1),
('sv-w452','swedish','white','Vad grannen hör genom väggen varje fredag kväll.',1),
('sv-w453','swedish','white','Kronprinsessans hemliga Instagram.',1),
('sv-w454','swedish','white','En yrkesutbildning i att bli professionell hora.',1),
('sv-w455','swedish','white','Det som Volvo-chefen gömmer i sitt handskfack.',1),
('sv-w456','swedish','white','En gråtande man i kostym utanför Systembolaget.',1),
('sv-b204','swedish','black','Sverige är inte redo för _.',1),
('sv-b205','swedish','black','Forskare har äntligen bevisat att _ orsakar klimatförändringarna.',1),
('sv-b206','swedish','black','På sin dödsbädd viskade statsministern: "_".',1),
('sv-b207','swedish','black','IKEA lanserar sin nya produkt: _. Pris: 149 kr.',1),
('sv-b208','swedish','black','Enligt en ny rapport från Folkhälsomyndigheten är _ den vanligaste dödsorsaken bland medelålders svenska män.',1),
('sv-b209','swedish','black','Under nästa val kommer S att köra hela sin kampanj på _.',1),
('sv-b210','swedish','black','Min terapeut sa att jag måste sluta med _, men det känns bara så bra.',1),
('sv-b211','swedish','black','Det visade sig att Nobelpriset i medicin 2025 gick till uppfinnaren av _.',1),
('sv-b212','swedish','black','Sverigedemokraterna har lagt fram ett förslag om att förbjuda _.',1),
('sv-b213','swedish','black','Kungen avslutade sitt tal med: "Och låt oss aldrig glömma vikten av _".',1),
('sv-b214','swedish','black','I den hemliga delen av Spotify Wrapped stod det: "Du lyssnade 847 gånger på _".',1),
('sv-b215','swedish','black','Enligt nya EU-regler måste alla medborgare deklarera sin _.',1),
('sv-b216','swedish','black','Min chef kallade det "teambuilding". Vi kallade det _.',1),
('sv-b217','swedish','black','Det enda som skiljer en politiker från en _ är lönen.',1),
('sv-b218','swedish','black','Årets julklapp på jobbet: _.',1),
('sv-b219','swedish','black','_ plus _ — det är vad som händer när Sverige går till val.',2),
('sv-b220','swedish','black','Doktorn tittade allvarligt på mig och sa: "Ni har _ i _". Jag visste inte om jag skulle skratta eller gråta.',2),
('sv-b221','swedish','black','På dejten beställde han _, berättade om sin _, och undrade om jag ville se hans _.',3),
('sv-b222','swedish','black','_ är det nya _. Åtminstone enligt min farbror på Facebook.',2),
('sv-b223','swedish','black','Välkommen till Sverige — vi erbjuder _, _, och en kronisk rädsla för att prata med _.',3)
ON CONFLICT (id) DO NOTHING;
