-- Swedish XL pack (swedish-xl): 75 white + 25 black cards.

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('v5m2oo7crs2c','swedish-xl','white','En genomvåt MILF från Nacka.',1),
('yqxo3nw3oc26','swedish-xl','white','Riksdagsdebatten som slutade med handjob.',1),
('t1ynncokt6fl','swedish-xl','white','Sverigedemokraternas Pride-float.',1),
('0s2j99d84gix','swedish-xl','white','En feminist med smuts under naglarna.',1),
('uqg7a9eg0e4e','swedish-xl','white','Det som luktade i Moderaternas omklädningsrum.',1),
('fxxq0wsfd5ta','swedish-xl','white','En öppen relation godkänd av Försäkringskassan.',1),
('1h6qs2y9k42j','swedish-xl','white','Tantens hemliga Pornhub-konto.',1),
('63pw47n33g15','swedish-xl','white','En väldigt liten penis med väldigt stor självkänsla.',1),
('acrl0agjfidq','swedish-xl','white','Det som fastnade i Volvons baksäte.',1),
('tv5fminlkgea','swedish-xl','white','En klimataktivist som flyger business class till sin orgie.',1),
('n7fbiebe8o6b','swedish-xl','white','Kronprinsessans vibrator med kunglig monogram.',1),
('ji9ebhipb6p5','swedish-xl','white','En rysk troll som onanerar till GDPR.',1),
('jjzo59i0864l','swedish-xl','white','Lögndetektorn som Aftonbladet köpte men aldrig använde.',1),
('n5g99pqenu4p','swedish-xl','white','En alkad medelålders man på Systembolaget med blombukett och skam.',1),
('6c6i1cva2cfr','swedish-xl','white','Det som hittades i Reinfeldt-villan vid husrannsakan.',1),
('ye9tvkvubapc','swedish-xl','white','En doktorand som säljer nakenbilder för att klara hyran.',1),
('3439sr67sf3w','swedish-xl','white','Göteborgs stads officiella fetischklubb.',1),
('xy58fsr31qko','swedish-xl','white','En hårding från Norrland med mjuka händer.',1),
('u8b9oeefd35o','swedish-xl','white','Det som polisen blåste förbi i Rinkeby.',1),
('e8t6nhj3pj8x','swedish-xl','white','En sorgsen kuk i ett tomt IKEA-sovrum.',1),
('73f8yj6mg1ux','swedish-xl','white','Birgitta Ohlssons Onlyfans.',1),
('uno78k3bg964','swedish-xl','white','En tantvibb med tre hastigheter och kommunal finansiering.',1),
('6epim4lmt5ld','swedish-xl','white','Det våta ljutet från Twitterdebatten.',1),
('ju4vkc8vsybr','swedish-xl','white','En bonde från Dalarna med ovanligt nära relation till sina djur.',1),
('xnom12e3gj2u','swedish-xl','white','Svaret på varför Melodifestivalen alltid vinner på hemmaplan.',1),
('6hs4wuj3yy72','swedish-xl','white','En anal penetrering med politisk majoritet.',1),
('jylmjq31x7hr','swedish-xl','white','Det hemliga syftet med Liseberg på natten.',1),
('u68042ibcuc7','swedish-xl','white','En transkvinna som vinner Fröken Sverige och Sverige mår bra.',1),
('9obyfrdlvzz7','swedish-xl','white','Prinsessan Madeleines dejtinghistorik.',1),
('94soa48q1qc3','swedish-xl','white','En deprimerad kille från Linköping med tre katter och ett abonnemang.',1),
('pprkr9c0m7we','swedish-xl','white','Det som Aftonbladet kallar "exklusivt" men alla redan vet.',1),
('1lbw0qkoet14','swedish-xl','white','En happy ending på Stadsbiblioteket i Malmö.',1),
('xuzsftvar8tm','swedish-xl','white','Löneglappet mellan en riksdagsledamot och en prostituerad.',1),
('u7sjelyk1zoi','swedish-xl','white','En förvirrad pensionär på fel Pride.',1),
('jumbiopm8f2w','swedish-xl','white','Det som mammas nya kille gömt i källaren.',1),
('ywk19d2lq200','swedish-xl','white','En ambitiös praktikant på Expressens nöjesredaktion.',1),
('ah9qkubqyvid','swedish-xl','white','Kung Carl Gustafs semesterfoto som läckte.',1),
('29tbsv5yt8dj','swedish-xl','white','En smygröstande SD-are i regnrock.',1),
('q5mwqi1zxdge','swedish-xl','white','Det som Folkhälsomyndigheten egentligen menar med "riskbeteende".',1),
('sybbdlnmb1eu','swedish-xl','white','En trosviss kristdemokrat med Grindr-konto.',1),
('umcdzxphfqxg','swedish-xl','white','Det fuktigaste som hänt i Almedalen.',1),
('z4zvvif62eqj','swedish-xl','white','En kommunalpolitiker med lite för nära relation till kommunens kassa.',1),
('n11zcoeinqpr','swedish-xl','white','Tre öl och ett misslyckande på Stureplan.',1),
('jrd4biu50vn3','swedish-xl','white','En socionom i kris.',1),
('5p4t9p9zuaz8','swedish-xl','white','Det som Aftonbladets sexspalt aldrig vågat publicera.',1),
('6o1zjfdixr06','swedish-xl','white','En porrfilm inspelad i Skåne med danska undertitlar.',1),
('jp7jz79fb1d8','swedish-xl','white','Det som grannen skrek under sin dejt.',1),
('x0tkapdsl5o9','swedish-xl','white','En rektor som förklarar vad "pedagogisk frihet" egentligen innebär.',1),
('3oo03uv8iwf1','swedish-xl','white','Miljöpartiets hemliga köttfest.',1),
('4dja1873iz50','swedish-xl','white','Det som fastnade i håret på Nobelgalan.',1),
('jh9pdvzyvs8f','swedish-xl','white','En SEO-optimerad kärleksakt.',1),
('yp2y7i6sghz8','swedish-xl','white','Statsrådets hemliga hobby som PR-teamet döljer.',1),
('qcy3ycstd4fi','swedish-xl','white','En avhoppad Jehovas vittne med väldigt mycket att ta igen.',1),
('gjwy80qefums','swedish-xl','white','Det som Tele2 gömmer i användarvillkoren, sida 47.',1),
('yhn2v07j79c7','swedish-xl','white','En naken löprunda runt Djurgården vid midnatt.',1),
('m04visk6j819','swedish-xl','white','En bitter divorcee från Östermalm med flaskviner och hämndplaner.',1),
('epckcf8uhnru','swedish-xl','white','Det som fastnade i rulltrappan på Åhlens.',1),
('u5z5ka90i956','swedish-xl','white','En autosvar som avslöjar för mycket.',1),
('jn1tmo0yrzlp','swedish-xl','white','Polisens julbord 2024.',1),
('en127807ftdn','swedish-xl','white','En sodomit med god kösmak och ännu bättre vinlista.',1),
('xucupx13hftj','swedish-xl','white','Det som SÄPO blundade för under femton år.',1),
('ydcu7h6f9uip','swedish-xl','white','En kändis som "tar en paus från sociala medier" men egentligen är på rehab.',1),
('j83h5kldcfc2','swedish-xl','white','En gammal gubbe med för mycket pengar och för lite skam.',1),
('t0ku5whsuc7m','swedish-xl','white','Det våtaste som hänt i Höganäs.',1),
('dzwhiqmcp03k','swedish-xl','white','En lärarinna med hemlig hobby och ännu hemligare garderob.',1),
('csgqr2ik7swy','swedish-xl','white','Saabs nästa produkt: ett stridsflyg med inbyggd vibrationsfunktion.',1),
('vx1ngj4divoq','swedish-xl','white','En partiledare som tappat kontrollen över sin kropp och sitt parti.',1),
('994i9b19fb94','swedish-xl','white','Det som hela grannskapet hörde men ingen pratar om.',1),
('fa21jy2y9xsa','swedish-xl','white','En influencer med 800k följare och noll självkänsla.',1),
('hsgg6xjjrcb2','swedish-xl','white','En kusin från Norrköping med väldigt fria värderingar.',1),
('f73cryqn450v','swedish-xl','white','Det som Systembolaget inte berättar om fredagsstängning.',1),
('g811d3n9vox7','swedish-xl','white','En medelålders man i kris som köpt motorcykel och läderbyxor.',1),
('lbiu9bjz5aws','swedish-xl','white','Det som hände på konferensen i Sälen som stannar i Sälen.',1),
('tq5iqy5blkq3','swedish-xl','white','En porrfilm med för realistisk dialog.',1),
('nsgc2ygdf03x','swedish-xl','white','Statsministerns googlesökningar en söndagsnatt.',1),
('64auspgei90g','swedish-xl','black','Varför gråter han egentligen? För att _.',1),
('hzbowxdlch9f','swedish-xl','black','Nya studier visar att _ botar depression bättre än antidepressiva.',1),
('2aydjm89eyf0','swedish-xl','black','IKEA:s nya bästsäljare heter _. Leveranstid: 6–8 veckor.',1),
('wrpkjch7bdif','swedish-xl','black','Vad hittar du alltid under en riksdagsledamots skrivbord? _.',1),
('bdky6nvlt8g0','swedish-xl','black','Folkhälsomyndigheten varnar nu för risker med _. Sverige bryr sig inte.',1),
('9y0akurhkaa8','swedish-xl','black','Årets mest sökta ord på Pornhub Sverige: _.',1),
('zgxmj0yszyc2','swedish-xl','black','Det enda som håller ihop den svenska regeringskoalitionen är _.',1),
('m84a6rjsbjqj','swedish-xl','black','Min psykolog sa att jag borde öppna upp mig. Då berättade jag om _. Nu har hon sjukskrivit sig.',1),
('g5hxdxm94mwe','swedish-xl','black','Sverige förlorade EM-kvalet på grund av _.',1),
('x30m4wkrl19g','swedish-xl','black','Vad är skillnaden mellan en lobbyist och _? Lobbyisten tar betalt i förskott.',1),
('rnj2f9qti3df','swedish-xl','black','Snapchatläckan avslöjade att partiledaren i hemlighet älskar _.',1),
('jf4o0sovyxll','swedish-xl','black','Det senaste från Rosenbad: regeringen har beslutat att _ nu är lagligt.',1),
('v5fzpgc77037','swedish-xl','black','Expressen har källor som bekräftar att kungen i hemlighet ägnar sig åt _.',1),
('b9tzbwpxs7b2','swedish-xl','black','Enligt en ny Sifo-undersökning vill 73% av svenskarna förbjuda _.',1),
('iad6zplkh13q','swedish-xl','black','Nobelpriset i litteratur gick i år till författaren av _.',1),
('qyof9824exdh','swedish-xl','black','Arbetsförmedlingens nya karriärtest rekommenderar alla över 50 att bli _.',1),
('b47oigrbraq6','swedish-xl','black','SVT:s nya dokusåpa: "Ensam med _".',1),
('uyythj5hcnff','swedish-xl','black','Det som alla tänker på under Melodifestivalen men ingen säger: _.',1),
('dptasbz5ik09','swedish-xl','black','Vad är det värsta man kan hitta i en politicians telefonhistorik? _.',1),
('m4e9e0gotaje','swedish-xl','black','Sverige 2026: det enda som fortfarande fungerar är _.',1),
('owk5os288ai5','swedish-xl','black','_ plus _ är den perfekta svenska dejten enligt Tinder-data.',2),
('kpw5u45lw6lk','swedish-xl','black','På presskonferensen förklarade ministern lugnt att _ berodde på _, och att ingen skulle behöva ta ansvar för _.',3),
('o3texjuibi31','swedish-xl','black','Välkommen till Almedalen: här hittar du _, _, och lukten av _.',3),
('fzcql56ezbim','swedish-xl','black','Den nya svenska sexualupplysningsfilmen handlar om _ och _. Visas inte för under 15.',2),
('l5jqcaqs0n3n','swedish-xl','black','_ är förbjudet i Sverige. _ är däremot helt lagligt och subventionerat av staten.',2)
ON CONFLICT (id) DO NOTHING;

