-- English XL pack (english-xl): 75 white + 25 black cards.

INSERT INTO cah_cards (id, pack, type, text, pick) VALUES
('95kp536tmy7c','english-xl','white','A Tinder date who smells like regret and Lynx Africa.',1),
('amrs13nujf45','english-xl','white','Boris Johnson''s pubic hair.',1),
('1n83u0jdv8ve','english-xl','white','An erection at a funeral.',1),
('qaw779q6y5jq','english-xl','white','The Pornhub category that shall not be named.',1),
('6evy707czc51','english-xl','white','A priest with a surprisingly detailed knowledge of bondage.',1),
('n9qvap1alg91','english-xl','white','Accidentally texting your mum instead of your dealer.',1),
('fez6u61rx4kp','english-xl','white','A LinkedIn post about a threesome framed as "professional growth".',1),
('solhrx47bvwe','english-xl','white','The Queen''s browser history.',1),
('1m04a7x8y9yi','english-xl','white','A tantric sex workshop in a WeWork meeting room.',1),
('zij9cd5yiu6k','english-xl','white','Elon Musk''s ninth child''s birth certificate.',1),
('oun607lyxezc','english-xl','white','A colonoscopy live-streamed on Twitch.',1),
('gfmxj2f53x69','english-xl','white','The last Google search before a very suspicious ER visit.',1),
('nw7dr0rgv858','english-xl','white','Sending a dick pic to the company-wide Slack.',1),
('evv5t7zsjl2y','english-xl','white','A sex worker who accepts air miles.',1),
('1nkjzdij3a08','english-xl','white','The wet sound from HR''s office.',1),
('4cuum9zgsvsx','english-xl','white','A conservative MP''s Grindr profile.',1),
('61p7f2q8fb29','english-xl','white','A sad, lonely erection at 3am.',1),
('xft63heytpbz','english-xl','white','The Pope''s safe word.',1),
('1a2pxx9lhwgv','english-xl','white','Surprise anal from the housing market.',1),
('5vy49gmx2dvg','english-xl','white','A wellness influencer who sells her bathwater and her soul.',1),
('6frwgw04tf8c','english-xl','white','Accidentally moaning your ex''s name at your own wedding.',1),
('3ez951wr2wxc','english-xl','white','A fart that clears a courtroom.',1),
('rr5w4m8t5j60','english-xl','white','The thing your therapist writes down but never says out loud.',1),
('2med9o9ssqo1','english-xl','white','A cryptocurrency bro explaining his portfolio from a van.',1),
('bp8qcqjrsx6u','english-xl','white','An NHS waiting list for a handjob.',1),
('jkk3c4f027zu','english-xl','white','A sentient sex toy with attachment issues.',1),
('1qhgu7frg69q','english-xl','white','The moment a vegan discovers bacon.',1),
('jeliirek350o','english-xl','white','Donald Trump''s search history during executive time.',1),
('cht7nywyyvcx','english-xl','white','A blowjob in exchange for solving the climate crisis.',1),
('475z6ctfud8i','english-xl','white','Grandma''s secret OnlyFans.',1),
('vr8ef45blb2b','english-xl','white','The thing that fell out during the marathon.',1),
('hr1ftens39t6','english-xl','white','A divorce settlement that includes the fleshlight.',1),
('c9wgvmc0sih9','english-xl','white','A badly timed queef in a silent yoga class.',1),
('9hghnq1y0jcx','english-xl','white','The hidden camera that was definitely not there by accident.',1),
('l1zci64lg1js','english-xl','white','A politician caught with his trousers down — literally.',1),
('vdcv0jyorubx','english-xl','white','An aggressive prostate exam from a passive-aggressive doctor.',1),
('evo3zewi34i4','english-xl','white','Two consenting adults and a deeply confused Roomba.',1),
('p16waz3k0jdz','english-xl','white','A motivational poster about anal hygiene.',1),
('p8tld4956x6s','english-xl','white','The look on the plumber''s face.',1),
('m8gfpdw2eh62','english-xl','white','King Charles''s private communication with his houseplants.',1),
('5jvjjb66g4er','english-xl','white','A midlife crisis with excellent thrusting technique.',1),
('h3ee3ku4ji09','english-xl','white','The HR email that should have been a phone call.',1),
('y0k8apl2igac','english-xl','white','A corporate team-building exercise that ended in lawsuits.',1),
('kduxp95lu4sk','english-xl','white','An orgasm that sounded like a dial-up modem.',1),
('12r8f5vntarw','english-xl','white','The Airbnb review that got the listing taken down.',1),
('07ocnpdtppys','english-xl','white','Getting ghosted by your dominatrix.',1),
('6k9epegfu2zi','english-xl','white','A pensioner''s surprisingly specific requests at the pharmacy.',1),
('cfnszvld1yo2','english-xl','white','The thing that made the Uber driver give one star.',1),
('2l9efajbf5nu','english-xl','white','An NFT of someone''s genitals bought by a sitting senator.',1),
('ybb9n0m6hm8g','english-xl','white','A WeightWatchers orgy.',1),
('nauhsk755tjt','english-xl','white','The TripAdvisor review of a Bangkok massage parlour.',1),
('xgzsvdkbtg3m','english-xl','white','Accidentally leaving your sex playlist on during a dinner party.',1),
('scntw2o503hg','english-xl','white','A police report that uses the word "lubricated" four times.',1),
('0eyu2ssa40np','english-xl','white','The Etsy shop selling handmade butt plugs as "artisan candles".',1),
('nbzp71kd52cf','english-xl','white','A fertility clinic with suspiciously cheerful staff.',1),
('ltmvapgwi7jd','english-xl','white','Matt Hancock''s deleted texts.',1),
('i9tyra4joy17','english-xl','white','A sex scene written entirely in corporate jargon.',1),
('iz3qdkryawpc','english-xl','white','The thing the hotel cleaner found and never reported.',1),
('6m2syfcvp1cm','english-xl','white','An incognito window with seventeen tabs open.',1),
('5nuwsti7l1wy','english-xl','white','Two words: "surprise inspection".',1),
('mpudmynbe530','english-xl','white','A leaked diplomatic cable about Angela Merkel''s personal life.',1),
('rfv5dhc3tgsy','english-xl','white','The noise from next door every single Thursday night.',1),
('1mxpevsjrjpr','english-xl','white','A badly positioned GoPro at a gender reveal party.',1),
('31m2kbiswtc5','english-xl','white','Sending your nudes to the wrong WhatsApp group.',1),
('r234bj3zwla2','english-xl','white','A life coach who charges by the orgasm.',1),
('1isui4wex5ob','english-xl','white','Fifty-seven years of repressed Catholic guilt released all at once.',1),
('ukv22ywkr1vd','english-xl','white','A Zoom call where someone forgot to turn off the camera.',1),
('pfidmu56nkuh','english-xl','white','The MI6 file that would end three careers and one marriage.',1),
('y6yee0197e4t','english-xl','white','A pub quiz question about clitoral anatomy that got the landlord cancelled.',1),
('ppmgbbg3d9g7','english-xl','white','The medical term your GP used that you had to Google immediately after.',1),
('qujq2mpr279i','english-xl','white','A cryptocurrency that''s backed entirely by sexual favours.',1),
('poaf1hj91oow','english-xl','white','The reason your neighbour bought soundproofing foam.',1),
('csluoj4dh3f3','english-xl','white','A sext sent to the family group chat.',1),
('svl8hsuflibi','english-xl','white','An A&E visit on Valentine''s Day with a very specific complaint.',1),
('adyv56vpr2ge','english-xl','white','The wedding speech that ended three relationships.',1),
('spxa801034wq','english-xl','black','Scientists have confirmed that _ is now the leading cause of erectile dysfunction.',1),
('cfxrojzqj41g','english-xl','black','The government has announced a new tax on _. Brits are furious.',1),
('06i0d5xt6i9j','english-xl','black','On his deathbed, he whispered: "_".',1),
('9lzwmb1rimwk','english-xl','black','New IKEA product: _. Assembly requires two people and no dignity.',1),
('ptunm4vh3u5j','english-xl','black','_ is now available on the NHS. The waiting list is 4 years.',1),
('mbvazegbdzw0','english-xl','black','Breaking news: _ found in the Prime Minister''s bathroom.',1),
('5vl3sge4rdos','english-xl','black','My therapist told me to let go of _. I''m suing her.',1),
('vye3a2arhdw2','english-xl','black','The Nobel Peace Prize this year went to the inventor of _.',1),
('hetvuda9hy70','english-xl','black','Pornhub''s most searched term in the UK in 2025: _.',1),
('c9qi48anvk2l','english-xl','black','According to new research, _ is more addictive than cocaine.',1),
('ld26ipvlvsnq','english-xl','black','The Ofsted inspector''s report described the school''s approach to _ as "outstanding".',1),
('vhd6noj4enur','english-xl','black','Studies show that 9 out of 10 politicians have secretly experimented with _.',1),
('acbpvndj2wdk','english-xl','black','Amazon''s new Alexa feature will now remind you daily to do _.',1),
('st6giq0mjfda','english-xl','black','The safe word was _. Nobody used it.',1),
('eqw6pmzc5hwe','english-xl','black','According to WikiLeaks, the CIA has been covertly funding _ since 1987.',1),
('0akz3dl4ozul','english-xl','black','What did they find in the cabinet minister''s briefcase? _.',1),
('mqfp61s8hmon','english-xl','black','The autopsy revealed an unexpected quantity of _.',1),
('mvnmuvbzc3e3','english-xl','black','Apple''s new product: _. Starting at £1,299.',1),
('p9o134vutab3','english-xl','black','The thing nobody mentions at Christmas dinner: _.',1),
('4wf0opbggdqe','english-xl','black','What''s the only thing holding Western democracy together right now? _.',1),
('dr8pgmcri493','english-xl','black','The job interview took a turn when the candidate mentioned _ and _.',2),
('5y6lxdp31180','english-xl','black','_ and _ walk into a bar. The barman calls the police about _.',3),
('0uo7ej6m6bl9','english-xl','black','The sex tape featured _, _, and a disappointing amount of _.',3),
('jo9z2owx01x7','english-xl','black','According to the leaked documents, the affair involved _ and _. The _ has since resigned.',3),
('j0bx8kpky11j','english-xl','black','_ is the new _. At least that''s what my _ keeps telling me.',3)
ON CONFLICT (id) DO NOTHING;

